(function installJayumintonAdminUnlimitedSelectionV2072(){
'use strict';
if(typeof IS_ADMIN!=='undefined'&&!IS_ADMIN)return;
if(window.__JAYUMINTON_ADMIN_UNLIMITED_SELECTION_V2072__)return;
window.__JAYUMINTON_ADMIN_UNLIMITED_SELECTION_V2072__=true;
/* Disable the old 2/3/4-person popup selector before its script executes. */
window.__JAYUMINTON_ADMIN_MULTI_ACTION_V2053__=true;
window.__JAYUMINTON_ADMIN_MULTI_ACTION_V2047__=true;
window.__JAYUMINTON_ADMIN_CONTINUE_SELECTION_V2067__=true;

var selected=new Set(), mode='', targets=[], busy=false, ephemeralTemp=new Set();
var CARD_SELECTOR='.member,.person,.quick-member,.member-card,.member-item,.player-card,.court-player,[data-member-id],[data-memberid],[data-player-id]';
var ID_SELECTOR='[data-member-id],[data-memberid],[data-player-id],[data-id],[data-member]';
function root(){return document.getElementById('adminApp');}
function state(){try{return typeof STATE!=='undefined'&&STATE?STATE:null;}catch(_){return null;}}
function memberId(el){if(!el||!el.getAttribute)return '';for(var k of ['data-member-id','data-memberid','data-player-id','data-id','data-member']){var v=el.getAttribute(k);if(v)return String(v);}var n=el.querySelector&&el.querySelector(ID_SELECTOR);return n?memberId(n):'';}
function cardFrom(target){if(!target||!target.closest)return null;var c=target.closest(ID_SELECTOR)||target.closest(CARD_SELECTOR);if(!c||!c.closest('#adminApp')||c.classList.contains('empty')||c.classList.contains('quick-empty-slot'))return null;return memberId(c)?c:null;}
function memberById(id){var s=state();return s&&Array.isArray(s.members)?s.members.find(function(m){return String(m.id)===String(id);})||null:null;}
function rpc(name,args){return typeof window.server==='function'?window.server(name,Array.isArray(args)?args:[]):Promise.reject(new Error('Cloudflare 서버 연결을 찾을 수 없습니다.'));}
function unwrap(v){for(var i=0;i<3;i++){if(v&&v.state&&typeof v.state==='object'){v=v.state;continue;}break;}return v;}
function renderStateSafe(v){var s=unwrap(v);if(s&&typeof renderState==='function')renderState(s);}
function toast(text,bad){var old=document.getElementById('jmUnlimitedToast');if(old)old.remove();var n=document.createElement('div');n.id='jmUnlimitedToast';n.textContent=String(text||'');n.style.cssText='position:fixed;left:50%;top:max(10px,env(safe-area-inset-top));transform:translateX(-50%);z-index:2147483647;padding:9px 13px;border-radius:11px;background:'+(bad?'#991b1b':'#111827')+';color:#fff;font-size:13px;font-weight:900;box-shadow:0 8px 24px rgba(0,0,0,.25)';document.body.appendChild(n);setTimeout(function(){n.remove();},1900);}
function allIds(){var s=state();return s&&Array.isArray(s.members)?s.members.map(function(m){return String(m.id);}).filter(Boolean):[];}
function tempIds(){var s=state(),out=new Set();(s&&Array.isArray(s.tempPairs)?s.tempPairs:[]).forEach(function(g){[g&&g.members,g&&g.pairA,g&&g.pairB].forEach(function(a){(Array.isArray(a)?a:[]).forEach(function(id){out.add(String(id));});});});ephemeralTemp.forEach(function(id){out.add(String(id));});return out;}
function ensureCheck(card,on){var badge=card.querySelector('.jm-unlimited-check');if(on){if(!badge){badge=document.createElement('span');badge.className='jm-unlimited-check';badge.textContent='✓';card.appendChild(badge);}}else if(badge)badge.remove();}
function paint(){var r=root();if(!r)return;var temps=tempIds();Array.prototype.forEach.call(r.querySelectorAll(CARD_SELECTOR+','+ID_SELECTOR),function(c){var id=memberId(c);if(!id)return;ensureCheck(c,selected.has(id));if(temps.has(id))c.classList.add('jm-temp-team-v2047');});var c=document.getElementById('jmUnlimitedCount');if(c)c.textContent=selected.size+'명 선택';var m=document.getElementById('jmUnlimitedMode');if(m)m.textContent=mode==='move'?'자리이동 대상 '+targets.length+'/'+selected.size:mode==='swap'?'교환 대상 '+targets.length+'/'+selected.size:'원하는 멤버를 계속 선택하세요';}
function clearSelection(){selected.clear();mode='';targets=[];paint();}
function selectAll(){allIds().forEach(function(id){selected.add(id);});paint();}
function setBusy(v){busy=!!v;var bar=document.getElementById('jmUnlimitedToolbar');if(bar)Array.prototype.forEach.call(bar.querySelectorAll('button,select'),function(el){el.disabled=busy;});}
function memberPayload(m,extra){return Object.assign({publicMemo:String(m.publicMemo||''),isNew:!!m.isNew,isSponsor:!!m.isSponsor,isDuplicate:!!m.isDuplicate},extra||{});}
async function refresh(){try{var s=await rpc('getPublicState',[null]);renderStateSafe(s);setTimeout(paint,0);}catch(_){} }
async function actionStatus(status){var ids=Array.from(selected);if(!ids.length)return toast('멤버를 먼저 선택하세요.',true);setBusy(true);try{var r=await rpc('setMemberStatus',[null,ids,status]);renderStateSafe(r);clearSelection();toast(ids.length+'명 상태 변경 완료');}catch(e){toast(e&&e.message||e,true);}finally{setBusy(false);}}
async function deleteSelected(){var ids=Array.from(selected);if(!ids.length)return toast('멤버를 먼저 선택하세요.',true);setBusy(true);try{var r=await rpc('deleteMembers',[null,ids]);renderStateSafe(r);clearSelection();toast(ids.length+'명 회원삭제 완료');}catch(e){toast(e&&e.message||e,true);}finally{setBusy(false);}}
function nextTeamLabel(){var max=0;allIds().forEach(function(id){var m=memberById(id),x=String(m&&m.teamLabel||'').match(/(\d+)/);if(x)max=Math.max(max,Number(x[1])||0);});return '팀 '+(max+1);}
async function setPermanent(){var ids=Array.from(selected);if(ids.length<2)return toast('2명 이상 선택하세요.',true);var label=nextTeamLabel(),bundle='team-'+Date.now()+'-'+Math.random().toString(36).slice(2);setBusy(true);try{for(var id of ids){var m=memberById(id);if(!m)continue;await rpc('updateMemberProfile',[null,id,String(m.name||''),String(m.gender||''),String(m.grade||''),String(m.experience||m.career||''),memberPayload(m,{bundleId:bundle,teamLabel:label})]);}await refresh();clearSelection();toast(ids.length+'명 영구팀설정 완료');}catch(e){toast(e&&e.message||e,true);}finally{setBusy(false);}}
async function clearPermanent(){var ids=Array.from(selected);if(!ids.length)return toast('멤버를 먼저 선택하세요.',true);setBusy(true);try{var r=await rpc('clearBundle',[null,ids]);renderStateSafe(r);clearSelection();toast('영구팀해제 완료');}catch(e){toast(e&&e.message||e,true);}finally{setBusy(false);}}
function locate(id){var s=state();if(!s)return null;for(var n of ['1','2','3','4'])if(Array.isArray(s.courts&&s.courts[n])&&s.courts[n].map(String).indexOf(String(id))>=0)return {type:'court',key:n};var w=Array.isArray(s.waitGroups)?s.waitGroups:[];for(var i=0;i<w.length;i++)if(Array.isArray(w[i])&&w[i].map(String).indexOf(String(id))>=0)return {type:'wait',key:String(i+1)};return {type:'active',key:'active'};}
function groupChunks(ids){var map={};ids.forEach(function(id){var l=locate(id),k=l.type+'|'+l.key;(map[k]||(map[k]={loc:l,ids:[]})).ids.push(id);});var out=[];Object.keys(map).forEach(function(k){var item=map[k];if(item.loc.type==='active'){item.ids.forEach(function(id){ephemeralTemp.add(id);});return;}for(var i=0;i<item.ids.length;i+=4){var chunk=item.ids.slice(i,i+4);if(chunk.length>=2)out.push({members:chunk,pairA:chunk.slice(0,2),pairB:chunk.slice(2,4),zone:item.loc.type,createdAt:Date.now()});else chunk.forEach(function(id){ephemeralTemp.add(id);});}});return out;}
async function setTemporary(){var ids=Array.from(selected);if(ids.length<2)return toast('2명 이상 선택하세요.',true);setBusy(true);try{var s=state(),existing=Array.isArray(s&&s.tempPairs)?s.tempPairs.slice():[];existing=existing.filter(function(g){var a=[];[g.members,g.pairA,g.pairB].forEach(function(x){(Array.isArray(x)?x:[]).forEach(function(v){a.push(String(v));});});return !ids.some(function(id){return a.indexOf(String(id))>=0;});});var groups=groupChunks(ids);var r=await rpc('setTempPairs',[null,existing.concat(groups)]);renderStateSafe(r);ids.forEach(function(id){if(locate(id).type==='active')ephemeralTemp.add(id);});clearSelection();setTimeout(paint,0);toast(ids.length+'명 임시팀설정 완료');}catch(e){toast(e&&e.message||e,true);}finally{setBusy(false);}}
async function clearTemporary(){var ids=Array.from(selected);if(!ids.length)return toast('멤버를 먼저 선택하세요.',true);setBusy(true);try{var s=state(),existing=Array.isArray(s&&s.tempPairs)?s.tempPairs.slice():[];existing=existing.filter(function(g){var a=[];[g.members,g.pairA,g.pairB].forEach(function(x){(Array.isArray(x)?x:[]).forEach(function(v){a.push(String(v));});});return !ids.some(function(id){return a.indexOf(String(id))>=0;});});ids.forEach(function(id){ephemeralTemp.delete(id);});var r=await rpc('setTempPairs',[null,existing]);renderStateSafe(r);clearSelection();setTimeout(paint,0);toast('임시팀해제 완료');}catch(e){toast(e&&e.message||e,true);}finally{setBusy(false);}}
function parseEmpty(el){if(!el)return null;var raw=String(el.getAttribute&&el.getAttribute('onclick')||'');var m=raw.match(/handleEmptySlotTap\(['\"](court|wait)['\"],['\"]?([^,'\")]+)['\"]?,\s*(\d+)/);if(m)return {type:m[1],key:m[1]==='wait'?String(Number(m[2])+1):String(m[2])};m=raw.match(/handleMemberWaitEmptyTap\((\d+),/);if(m)return {type:'wait',key:String(Number(m[1])+1)};return null;}
async function executeMoveTargets(){var src=Array.from(selected);if(src.length!==targets.length)return;setBusy(true);try{for(var i=0;i<src.length;i++){var t=targets[i];await rpc('moveOrSwapMember',[null,src[i],t.type,t.type==='wait'?String(Number(t.key)-1):String(t.key),'']);}await refresh();clearSelection();toast(src.length+'명 자리이동 완료');}catch(e){toast(e&&e.message||e,true);mode='';targets=[];}finally{setBusy(false);paint();}}
async function executeSwapTargets(){var src=Array.from(selected);if(src.length!==targets.length)return;setBusy(true);try{for(var i=0;i<src.length;i++)await rpc('swapMembers',[null,[src[i]],[targets[i]]]);await refresh();clearSelection();toast(src.length+'명 교환 완료');}catch(e){toast(e&&e.message||e,true);mode='';targets=[];}finally{setBusy(false);paint();}}
function startMode(next){if(!selected.size)return toast('멤버를 먼저 선택하세요.',true);mode=next;targets=[];paint();toast(next==='move'?'이동할 빈자리를 선택하세요.':'교환할 상대 멤버를 선택하세요.');}
function handleClick(ev){if(busy)return;var r=root();if(!r||!r.contains(ev.target))return;var c=cardFrom(ev.target);if(mode==='swap'&&c){var id=memberId(c);if(selected.has(id)||targets.indexOf(id)>=0)return;ev.preventDefault();ev.stopImmediatePropagation();targets.push(id);paint();if(targets.length===selected.size)executeSwapTargets();return;}if(mode==='move'){var empty=ev.target.closest&&ev.target.closest('.empty,.quick-empty-slot,[onclick*="handleEmptySlotTap"],[onclick*="handleMemberWaitEmptyTap"]');var t=parseEmpty(empty);if(t){ev.preventDefault();ev.stopImmediatePropagation();targets.push(t);paint();if(targets.length===selected.size)executeMoveTargets();}return;}if(!c)return;var id=memberId(c);ev.preventDefault();ev.stopImmediatePropagation();if(selected.has(id))selected.delete(id);else selected.add(id);paint();}
function toolbar(){var bar=document.getElementById('jmUnlimitedToolbar');if(bar)return bar;bar=document.createElement('section');bar.id='jmUnlimitedToolbar';bar.className='card';bar.innerHTML='<div class="jm-u-head"><strong>멤버선택 · 상태변경 · 회원삭제</strong><span id="jmUnlimitedCount">0명 선택</span></div><div id="jmUnlimitedMode" class="jm-u-mode">원하는 멤버를 계속 선택하세요</div><div class="jm-u-grid"><button data-a="all">모두선택</button><button data-a="active">코트배정대기로 보내기</button><button data-a="perm">영구팀설정</button><button data-a="temp">임시팀설정</button><button data-a="perm-clear">영구팀해제</button><button data-a="temp-clear">임시팀해제</button><button data-a="move">자리이동</button><button data-a="swap">교환</button><select id="jmUnlimitedStatus"><option value="before">도착전</option><option value="rest">휴식</option><option value="away">귀가</option><option value="active">코트배정대기</option></select><button data-a="status">상태변경</button><button class="danger" data-a="delete">회원삭제</button><button data-a="clear">선택해제</button></div>';
var quick=document.getElementById('quickSelectedCount');var anchor=quick&&quick.closest('.card');var details=document.querySelector('.admin-setup-details');if(anchor&&anchor.parentNode)anchor.parentNode.insertBefore(bar,anchor);else if(details&&details.parentNode)details.parentNode.insertBefore(bar,details.nextSibling);else (r||document.body).prepend(bar);
bar.addEventListener('click',function(e){var b=e.target.closest('button[data-a]');if(!b)return;e.preventDefault();e.stopPropagation();var a=b.getAttribute('data-a');if(a==='all')selectAll();else if(a==='active')actionStatus('active');else if(a==='perm')setPermanent();else if(a==='temp')setTemporary();else if(a==='perm-clear')clearPermanent();else if(a==='temp-clear')clearTemporary();else if(a==='move')startMode('move');else if(a==='swap')startMode('swap');else if(a==='status')actionStatus(String(document.getElementById('jmUnlimitedStatus').value||'active'));else if(a==='delete')deleteSelected();else if(a==='clear')clearSelection();});return bar;}
function installStyle(){if(document.getElementById('jmUnlimitedStyle'))return;var s=document.createElement('style');s.id='jmUnlimitedStyle';s.textContent='#jmUnlimitedToolbar{margin:10px 0!important;padding:10px!important;box-shadow:0 3px 14px rgba(15,23,42,.10)!important}#jmUnlimitedToolbar .jm-u-head{display:flex;justify-content:space-between;gap:8px;align-items:center;margin-bottom:4px}#jmUnlimitedCount{font-size:12px;font-weight:900;color:#166534;background:#ecfdf5;border-radius:999px;padding:4px 8px;white-space:nowrap}.jm-u-mode{font-size:11px;color:#64748b;margin-bottom:7px}.jm-u-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:5px}.jm-u-grid button,.jm-u-grid select{min-width:0;min-height:38px;padding:5px 3px;font-size:10px;font-weight:900;border-radius:9px;white-space:normal}.jm-u-grid .danger{background:#c62828!important;color:#fff!important;border-color:#c62828!important}.jm-unlimited-check{position:absolute!important;right:3px!important;top:3px!important;z-index:30!important;width:19px!important;height:19px!important;border-radius:50%!important;background:#16a34a!important;color:#fff!important;display:flex!important;align-items:center!important;justify-content:center!important;font-size:13px!important;font-weight:1000!important;line-height:1!important;box-shadow:0 1px 4px rgba(0,0,0,.3)!important;pointer-events:none!important}#adminApp .member,#adminApp .person,#adminApp .quick-member,#adminApp .member-card,#adminApp .member-item,#adminApp .player-card,#adminApp .court-player{position:relative!important}.admin-setup-details .admin-member-bulk-panel{display:none!important}@media(max-width:620px){.jm-u-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.jm-u-grid button,.jm-u-grid select{font-size:9.5px;min-height:36px}}';(document.head||document.documentElement).appendChild(s);}
function boot(){var r=root();if(!r){setTimeout(boot,100);return;}installStyle();toolbar();r.addEventListener('click',handleClick,true);var q=false,newObs=new MutationObserver(function(){if(q)return;q=true;requestAnimationFrame(function(){q=false;toolbar();paint();});});newObs.observe(r,{childList:true,subtree:true});paint();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else setTimeout(boot,0);
})();
