(function installJayumintonAdminMultiActionV2047(){
  'use strict';
  if(typeof IS_ADMIN==='undefined'||!IS_ADMIN||window.__JAYUMINTON_ADMIN_MULTI_ACTION_V2047__)return;
  window.__JAYUMINTON_ADMIN_MULTI_ACTION_V2047__=true;
  var CARD_SELECTOR='.member,.person,.quick-member,.member-card,.member-item,.wait-card,.wait-item,.player-card,.court-player,[data-member-id],[data-memberid],[data-player-id]';
  var sourceIds=[],sourceGroup=null,phase='source',targets=[],targetKind='',tempTeamIds={};

  function ensureStyle(){
    var old=document.getElementById('jayuminton-admin-team-safety-v2037');if(old)old.remove();
    if(document.getElementById('jayuminton-admin-multi-action-v2047-style'))return;
    var s=document.createElement('style');s.id='jayuminton-admin-multi-action-v2047-style';
    s.textContent=''
      +'#adminApp .jm-source-selected{box-shadow:0 0 0 4px #16a34a!important;outline:2px solid rgba(22,163,74,.20)!important;outline-offset:1px!important}'
      +'#adminApp .jm-target-selected{box-shadow:0 0 0 4px #16a34a!important;outline:2px dashed #166534!important;outline-offset:1px!important}'
      +'#adminApp .jm-temp-team-v2047,#adminApp .jm-temp-pair{box-shadow:0 0 0 4px #d4a017!important;outline:2px solid rgba(212,160,23,.20)!important;outline-offset:1px!important}'
      +'.jm-multi-action{position:fixed;left:50%;bottom:18px;transform:translateX(-50%);z-index:2147483645;width:min(520px,calc(100vw - 24px));background:#fff;border:1px solid #e2e8f0;border-radius:20px;padding:14px;box-shadow:0 18px 55px rgba(15,23,42,.28);font-family:inherit}'
      +'.jm-multi-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:10px}.jm-multi-title{font-size:15px;font-weight:900;color:#111827}.jm-multi-count{font-size:12px;font-weight:800;color:#15803d;background:#f0fdf4;border-radius:999px;padding:5px 9px}'
      +'.jm-multi-help{font-size:12.5px;color:#64748b;line-height:1.45;margin-bottom:10px}.jm-multi-actions{display:grid;grid-template-columns:1fr 1fr 72px;gap:8px}.jm-multi-action button{border:0;border-radius:12px;min-height:44px;font-size:14px;font-weight:850;font-family:inherit}.jm-do-move{background:#dcfce7;color:#166534}.jm-do-team{background:linear-gradient(180deg,#e4b52a,#c9970d);color:white}.jm-do-cancel{background:#f1f5f9;color:#475569}.jm-do-team:disabled{opacity:.38}.jm-target-status{font-weight:850;color:#166534}';
    (document.head||document.documentElement).appendChild(s);
  }
  function app(){return document.getElementById('adminApp');}
  function memberCard(target){if(!target||!target.closest)return null;var c=target.closest(CARD_SELECTOR);if(!c||!c.closest('#adminApp')||c.classList.contains('empty')||c.classList.contains('quick-empty-slot'))return null;return c;}
  function cardId(card){if(!card)return '';var a=['data-member-id','data-memberid','data-player-id','data-id','data-member'];for(var i=0;i<a.length;i++){var v=card.getAttribute&&card.getAttribute(a[i]);if(v)return String(v);}var n=card.querySelector&&card.querySelector('[data-member-id],[data-memberid],[data-player-id],[data-id],[data-member]');if(n){for(var j=0;j<a.length;j++){var x=n.getAttribute(a[j]);if(x)return String(x);}}var raw=String(card.getAttribute&&card.getAttribute('onclick')||''),u=raw.match(/[0-9a-f]{8}-[0-9a-f-]{27,}/i);if(u)return u[0];return '';}
  function idsInside(root){var f={};if(!root||!root.querySelectorAll)return [];Array.prototype.forEach.call(root.querySelectorAll(CARD_SELECTOR),function(e){var id=cardId(e);if(id)f[id]=1;});return Object.keys(f);}
  function inferZone(node){for(var c=node,d=0;c&&d<9;c=c.parentElement,d++){var z=String((c.id||'')+' '+(typeof c.className==='string'?c.className:''));if(c.getAttribute&&((c.getAttribute('data-court')!=null)||(c.getAttribute('data-court-no')!=null)||(c.getAttribute('data-court-number')!=null))||/court|코트/i.test(z))return 'court';if(c.getAttribute&&((c.getAttribute('data-wait')!=null)||(c.getAttribute('data-wait-no')!=null)||(c.getAttribute('data-wait-group')!=null))||/wait|대기/i.test(z))return 'wait';}return '';}
  function compactGroup(card){var id=cardId(card);for(var n=card&&card.parentElement,d=0;n&&d<9;n=n.parentElement,d++){var ids=idsInside(n),zone=inferZone(n);if(zone&&ids.length>=1&&ids.length<=4&&ids.indexOf(id)>=0){ids=ids.map(String).sort();return {zone:zone,ids:ids,signature:zone+'|'+ids.join('|')};}}return null;}
  function eachCardForId(id,fn){var a=app();if(!a)return;var seen=[];Array.prototype.forEach.call(a.querySelectorAll(CARD_SELECTOR),function(e){if(cardId(e)!==String(id))return;var c=memberCard(e)||e;if(seen.indexOf(c)<0){seen.push(c);fn(c);}});}
  function clearClass(cls){var a=app();if(a)Array.prototype.forEach.call(a.querySelectorAll('.'+cls),function(e){e.classList.remove(cls);});}
  function renderSource(){clearClass('jm-source-selected');sourceIds.forEach(function(id){eachCardForId(id,function(c){c.classList.add('jm-source-selected');});});}
  function renderTargets(){clearClass('jm-target-selected');targets.forEach(function(t){if(t.kind==='member')eachCardForId(t.id,function(c){c.classList.add('jm-target-selected');});else if(t.el&&document.contains(t.el))t.el.classList.add('jm-target-selected');});}
  function renderYellow(){var a=app();if(!a)return;Array.prototype.forEach.call(a.querySelectorAll('.jm-temp-team-v2047,.jm-temp-pair'),function(e){e.classList.remove('jm-temp-team-v2047');e.classList.remove('jm-temp-pair');});Object.keys(tempTeamIds).forEach(function(id){if(tempTeamIds[id])eachCardForId(id,function(c){c.classList.add('jm-temp-team-v2047');});});}
  function tempIdsOf(p){return (Array.isArray(p&&p.members)?p.members:[]).concat(Array.isArray(p&&p.pairA)?p.pairA:[]).concat(Array.isArray(p&&p.pairB)?p.pairB:[]).map(String).filter(Boolean);}
  function absorb(state){tempTeamIds={};var ps=Array.isArray(state&&state.tempPairs)?state.tempPairs:[];ps.forEach(function(p){tempIdsOf(p).forEach(function(id){tempTeamIds[id]=1;});});renderYellow();}
  function rpc(name,args,ok,fail){var r=window.google&&window.google.script&&window.google.script.run;if(!r){if(fail)fail(new Error('서버 연결을 찾을 수 없습니다.'));return;}r.withSuccessHandler(function(x){if(ok)ok(x);}).withFailureHandler(function(e){if(fail)fail(e);})[name].apply(r,args);}
  function toast(t,bad){var o=document.getElementById('jm-admin-multi-toast');if(o)o.remove();var e=document.createElement('div');e.id='jm-admin-multi-toast';e.textContent=String(t||'');e.style.cssText='position:fixed;left:50%;bottom:92px;transform:translateX(-50%);z-index:2147483647;padding:10px 14px;border-radius:12px;background:'+(bad?'#991b1b':'#111827')+';color:#fff;font-size:14px;font-weight:800;box-shadow:0 8px 26px rgba(0,0,0,.22)';document.body.appendChild(e);setTimeout(function(){e.remove();},1800);}
  function resetAll(){sourceIds=[];sourceGroup=null;phase='source';targets=[];targetKind='';renderSource();renderTargets();renderPanel();renderYellow();}
  function panel(){var p=document.getElementById('jm-admin-multi-action');if(!p){p=document.createElement('div');p.id='jm-admin-multi-action';p.className='jm-multi-action';document.body.appendChild(p);}return p;}
  function renderPanel(){var p=document.getElementById('jm-admin-multi-action');if(!sourceIds.length){if(p)p.remove();return;}p=panel();if(phase==='target'){p.innerHTML='<div class="jm-multi-head"><div class="jm-multi-title">'+sourceIds.length+'명 이동/교환</div><div class="jm-multi-count">대상 '+targets.length+'/'+sourceIds.length+'</div></div><div class="jm-multi-help">빈자리 '+sourceIds.length+'곳 또는 바꿀 사람 '+sourceIds.length+'명을 선택하세요.</div><div class="jm-multi-actions" style="grid-template-columns:1fr 90px"><button type="button" class="jm-back-source">사람 다시 선택</button><button type="button" class="jm-do-cancel">취소</button></div>';p.querySelector('.jm-back-source').onclick=function(e){e.stopPropagation();phase='source';targets=[];targetKind='';renderTargets();renderPanel();};p.querySelector('.jm-do-cancel').onclick=function(e){e.stopPropagation();resetAll();};return;}
    p.innerHTML='<div class="jm-multi-head"><div class="jm-multi-title">같은 '+(sourceGroup&&sourceGroup.zone==='court'?'코트':'대기번호')+'에서 선택</div><div class="jm-multi-count">'+sourceIds.length+'명 선택</div></div><div class="jm-multi-help">1~4명을 먼저 선택한 뒤 이동/교환 또는 팀설정을 누르세요.</div><div class="jm-multi-actions"><button type="button" class="jm-do-move">이동/교환</button><button type="button" class="jm-do-team" '+(sourceIds.length<2?'disabled':'')+'>팀설정</button><button type="button" class="jm-do-cancel">취소</button></div>';
    p.querySelector('.jm-do-move').onclick=function(e){e.stopPropagation();phase='target';targets=[];targetKind='';renderPanel();toast(sourceIds.length+'명과 바꿀 사람 또는 빈자리를 선택하세요.',false);};
    p.querySelector('.jm-do-team').onclick=function(e){e.stopPropagation();if(sourceIds.length>=2)saveTeam(sourceIds.slice(),sourceGroup&&sourceGroup.zone||'');};
    p.querySelector('.jm-do-cancel').onclick=function(e){e.stopPropagation();resetAll();};
  }
  function saveTeam(ids,zone){rpc('getPublicState',[null],function(state){var existing=Array.isArray(state&&state.tempPairs)?state.tempPairs.slice():[];existing=existing.filter(function(p){var all=tempIdsOf(p);return !ids.some(function(id){return all.indexOf(String(id))>=0;});});existing.push({members:ids.map(String),pairA:ids.slice(0,2).map(String),pairB:[],zone:zone,createdAt:Date.now()});rpc('setTempPairs',[null,existing],function(saved){var next=(saved&&saved.tempPairs)?saved:saved;absorb(next||{});ids.forEach(function(id){tempTeamIds[String(id)]=1;});resetAll();renderYellow();setTimeout(function(){rpc('getPublicState',[null],function(s){absorb(s);},function(){});},120);toast(ids.length+'명을 같은 팀으로 설정했습니다.',false);},function(e){toast(String(e&&e.message||e||'팀 설정에 실패했습니다.'),true);});},function(e){toast(String(e&&e.message||e||'현재 팀 정보를 불러오지 못했습니다.'),true);});}
  function emptyTarget(el){if(!el)return null;var raw=String(el.getAttribute('onclick')||'');var m=raw.match(/handleEmptySlotTap\(['\"]([^'\"]+)['\"],['\"]([^'\"]+)['\"],\s*(\d+)/);if(!m)return null;return {kind:'empty',type:String(m[1]),index:String(m[2]),slotIndex:Number(m[3]),el:el,key:'e|'+m[1]+'|'+m[2]+'|'+m[3]};}
  function currentState(){try{return typeof STATE!=='undefined'?STATE:null;}catch(_){return null;}}
  function locateMember(id){var st=currentState();if(!st)return null;var cs=st.courts||{};for(var k in cs){if(Array.isArray(cs[k])&&cs[k].map(String).indexOf(String(id))>=0)return {type:'court',index:String(k)};}var ws=st.waitGroups||[];for(var i=0;i<ws.length;i++){if(Array.isArray(ws[i])&&ws[i].map(String).indexOf(String(id))>=0)return {type:'wait',index:String(i)};}return null;}
  function addTarget(t){if(!t)return;if(targetKind&&targetKind!==t.kind){toast('빈자리와 사람은 섞어서 선택할 수 없습니다.',true);return;}var key=t.kind==='member'?'m|'+t.id:t.key;var at=-1;for(var i=0;i<targets.length;i++){var k=targets[i].kind==='member'?'m|'+targets[i].id:targets[i].key;if(k===key){at=i;break;}}if(at>=0){targets.splice(at,1);if(!targets.length)targetKind='';renderTargets();renderPanel();return;}if(targets.length>=sourceIds.length){toast('대상은 '+sourceIds.length+'명(곳)까지만 선택할 수 있습니다.',true);return;}targetKind=t.kind;targets.push(t);renderTargets();renderPanel();if(targets.length===sourceIds.length)executeMove();}
  async function executeMove(){var src=sourceIds.slice(),dst=targets.slice();if(src.length!==dst.length)return;var pin='';try{pin=typeof ADMIN_PIN_VALUE!=='undefined'?ADMIN_PIN_VALUE:'';}catch(_){}if(typeof server!=='function'){toast('이동 기능을 찾을 수 없습니다.',true);return;}var p=panel();if(p)p.style.pointerEvents='none';try{if(targetKind==='member'){await server('swapMembers',[pin,src,dst.map(function(t){return String(t.id);})]);}else{for(var i=0;i<src.length;i++){var t=dst[i];await server('moveOrSwapMember',[pin,String(src[i]),String(t.type),String(t.index),'']);}}resetAll();try{if(typeof renderState==='function')renderState();}catch(_){}toast(src.length+'명 이동/교환을 완료했습니다.',false);}catch(e){toast(String(e&&e.message||e||'이동/교환에 실패했습니다.'),true);phase='source';targets=[];targetKind='';renderTargets();renderPanel();}finally{var q=document.getElementById('jm-admin-multi-action');if(q)q.style.pointerEvents='';}}
  function sameSourceGroup(g){if(!sourceGroup||!g)return false;if(sourceGroup.signature===g.signature)return true;return sourceGroup.zone===g.zone&&sourceGroup.ids.some(function(id){return g.ids.indexOf(id)>=0;});}
  function onClick(event){if(event.button>0)return;if(event.target&&event.target.closest&&event.target.closest('#jm-admin-multi-action'))return;ensureStyle();
    if(phase==='target'){var emptyEl=event.target&&event.target.closest&&event.target.closest('.quick-empty-slot,.person.empty');if(emptyEl&&emptyEl.closest('#adminApp')){var et=emptyTarget(emptyEl);if(et){event.preventDefault();event.stopPropagation();if(event.stopImmediatePropagation)event.stopImmediatePropagation();addTarget(et);return;}}var tc=memberCard(event.target);if(tc){var tid=cardId(tc);if(!tid||sourceIds.indexOf(String(tid))>=0)return;var loc=locateMember(tid);if(!loc){toast('이 사람의 현재 위치를 찾지 못했습니다.',true);return;}event.preventDefault();event.stopPropagation();if(event.stopImmediatePropagation)event.stopImmediatePropagation();addTarget({kind:'member',id:String(tid),type:loc.type,index:loc.index,key:'m|'+tid});return;}return;}
    if(event.target&&event.target.closest&&event.target.closest('button,input,textarea,select,a,[role="button"]'))return;var card=memberCard(event.target);if(!card)return;var id=cardId(card),g=compactGroup(card);if(!id||!g)return;if(sourceIds.length&&!sameSourceGroup(g)){event.preventDefault();event.stopPropagation();if(event.stopImmediatePropagation)event.stopImmediatePropagation();toast('먼저 이동/교환 또는 팀설정을 선택하세요.',false);return;}event.preventDefault();event.stopPropagation();if(event.stopImmediatePropagation)event.stopImmediatePropagation();if(!sourceIds.length)sourceGroup=g;var at=sourceIds.indexOf(String(id));if(at>=0)sourceIds.splice(at,1);else if(sourceIds.length<4)sourceIds.push(String(id));else toast('한 번에 최대 4명까지 선택할 수 있습니다.',true);if(!sourceIds.length)sourceGroup=null;renderSource();renderPanel();renderYellow();}
  function watch(){var a=app();if(!a){setTimeout(watch,120);return;}ensureStyle();if(a.__jmV2047Observer)return;var pending=false;a.__jmV2047Observer=new MutationObserver(function(){if(pending)return;pending=true;(window.requestAnimationFrame||setTimeout)(function(){pending=false;ensureStyle();renderSource();renderTargets();renderYellow();},16);});a.__jmV2047Observer.observe(a,{childList:true,subtree:true});rpc('getPublicState',[null],function(s){absorb(s);},function(){});}
  ensureStyle();window.addEventListener('click',onClick,true);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch,{once:true});else setTimeout(watch,0);
})();
