(function installJayumintonAdminTeamLayoutV2063(){
'use strict';if(window.__JAYUMINTON_ADMIN_TEAM_LAYOUT_V2063__)return;window.__JAYUMINTON_ADMIN_TEAM_LAYOUT_V2063__=true;window.__JAYUMINTON_ADMIN_TEAM_LAYOUT_V2038__=true;
var SEL='.member,.person,.quick-member,.member-card,.member-item,.player-card,.court-player,[data-member-id],[data-memberid],[data-player-id]',PAL=['#6d28d9','#0891b2','#c2410c','#0f766e','#be185d','#4f46e5','#15803d','#a16207'];
function id(c){if(!c||!c.getAttribute)return '';for(var k of ['data-member-id','data-memberid','data-player-id','data-id','data-member']){var v=c.getAttribute(k);if(v)return String(v);}var n=c.querySelector&&c.querySelector('[data-member-id],[data-memberid],[data-player-id],[data-id],[data-member]');return n?id(n):'';}
function ms(){try{return STATE&&Array.isArray(STATE.members)?STATE.members:[];}catch(_){return [];}}function mby(i){return ms().find(function(m){return String(m.id||'')===String(i);})||null;}function key(m){return String(m&&(m.bundleId||m.teamId||m.teamLabel||m.team||m.teamName)||'').trim();}
function color(k,m){var own=String(m&&(m.teamColor||m.bundleColor)||'');if(/^#[0-9a-f]{6}$/i.test(own))return own;var keys=[];ms().forEach(function(x){var z=key(x);if(z&&keys.indexOf(z)<0)keys.push(z);});keys.sort();var i=keys.indexOf(k);return PAL[(i<0?0:i)%PAL.length];}
function cards(){var r=document.getElementById('adminApp'),o=[];if(!r)return o;Array.prototype.forEach.call(r.querySelectorAll(SEL),function(c){if(c.matches&&c.matches('.wait-card,.wait-item'))return;if(id(c)&&o.indexOf(c)<0)o.push(c);});return o;}
function sync(){var r=document.getElementById('adminApp');if(!r)return;Array.prototype.forEach.call(r.querySelectorAll('.wait-card,.wait-item'),function(e){e.classList.remove('has-member-team','jm-temp-team-v2047','jm-temp-pair');e.style.removeProperty('--member-team-color');});cards().forEach(function(c){var m=mby(id(c)),k=key(m);if(k){c.classList.add('has-member-team');c.style.setProperty('--member-team-color',color(k,m));}else{c.classList.remove('has-member-team');c.style.removeProperty('--member-team-color');}var isNew=!!(m&&(m.isNew===true||String(m.isNew)==='1'||String(m.isNew).toLowerCase()==='true'));c.classList.toggle('jm-admin-new-card',isNew);});}
function style(){if(document.getElementById('jm-team-v2063'))return;var s=document.createElement('style');s.id='jm-team-v2063';s.textContent='#adminApp .has-member-team{border-color:transparent!important;outline:3px solid var(--member-team-color,#6d28d9)!important;outline-offset:3px!important;box-shadow:0 0 0 6px #fff,0 0 0 9px var(--member-team-color,#6d28d9)!important}#adminApp .has-member-team.jm-temp-team-v2047,#adminApp .has-member-team.jm-temp-pair,#adminApp .jm-temp-team-v2047,#adminApp .jm-temp-pair{outline:5px solid #d4a017!important;outline-offset:1px!important;box-shadow:none!important}#adminApp .jm-admin-new-card{min-height:88px!important;padding-bottom:28px!important;overflow:visible!important}';(document.head||document.documentElement).appendChild(s);}
function boot(){style();sync();var r=document.getElementById('adminApp');if(!r){setTimeout(boot,100);return;}if(r.__jmTeamV2063)return;var q=false;r.__jmTeamV2063=new MutationObserver(function(){if(q)return;q=true;requestAnimationFrame(function(){q=false;sync();});});r.__jmTeamV2063.observe(r,{childList:true,subtree:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else setTimeout(boot,0);
})();