(function installJayumintonAdminCardInteractionV2045(){
  'use strict';
  if(typeof IS_ADMIN==='undefined'||!IS_ADMIN||window.__JAYUMINTON_ADMIN_CARD_INTERACTION_V2045__)return;
  window.__JAYUMINTON_ADMIN_CARD_INTERACTION_V2045__=true;
  var CARD_SELECTOR='.member,.person,.quick-member,.member-card,.member-item,.wait-card,.wait-item,.player-card,.court-player,[data-member-id],[data-memberid],[data-player-id]';
  var moveSelection=null,dialogOpen=false,tempPairIds={},nativeCleanup=false;

  function ensureStyle(){
    if(document.getElementById('jayuminton-admin-card-interaction-v2045-style'))return;
    var s=document.createElement('style');s.id='jayuminton-admin-card-interaction-v2045-style';
    s.textContent=''
      +'#adminApp .jm-move-selected{box-shadow:0 0 0 4px #16a34a!important;outline:2px solid rgba(22,163,74,.22)!important;outline-offset:1px!important}'
      +'#adminApp .jm-temp-pair-v2045,#adminApp .jm-temp-pair{box-shadow:0 0 0 4px #d4a017!important;outline:2px solid rgba(212,160,23,.22)!important;outline-offset:1px!important}'
      +'.jm-team-confirm-backdrop{position:fixed;inset:0;z-index:2147483646;background:rgba(15,23,42,.38);display:flex;align-items:center;justify-content:center;padding:24px;backdrop-filter:blur(4px);-webkit-backdrop-filter:blur(4px)}'
      +'.jm-team-confirm{width:min(370px,92vw);background:#fff;border:1px solid #e2e8f0;border-radius:24px;padding:24px 22px 20px;box-shadow:0 28px 80px rgba(15,23,42,.30);text-align:center;font-family:inherit}'
      +'.jm-team-confirm-icon{width:50px;height:50px;margin:0 auto 12px;border-radius:16px;display:flex;align-items:center;justify-content:center;background:#fff8db;border:1px solid #fde68a;font-size:25px}'
      +'.jm-team-confirm-title{font-size:20px;font-weight:900;color:#111827;margin:0 0 8px}.jm-team-confirm-sub{font-size:13.5px;line-height:1.55;color:#64748b;margin:0 0 20px}'
      +'.jm-team-confirm-actions{display:grid;grid-template-columns:1fr 1fr;gap:10px}.jm-team-confirm button{border:0;border-radius:14px;padding:13px 10px;font-size:15px;font-weight:800;min-height:46px}'
      +'.jm-team-confirm .jm-team-yes{background:linear-gradient(180deg,#e4b52a,#c9970d);color:#fff}.jm-team-confirm .jm-team-no{background:#f0fdf4;color:#15803d;border:1px solid #bbf7d0}';
    (document.head||document.documentElement).appendChild(s);
  }
  function memberCard(target){if(!target||!target.closest)return null;var c=target.closest(CARD_SELECTOR);return c&&c.closest('#adminApp')?c:null;}
  function cardId(card){if(!card)return '';var a=['data-member-id','data-memberid','data-player-id','data-id','data-member'];for(var i=0;i<a.length;i++){var v=card.getAttribute&&card.getAttribute(a[i]);if(v)return String(v);}var n=card.querySelector&&card.querySelector('[data-member-id],[data-memberid],[data-player-id],[data-id],[data-member]');if(n){for(var j=0;j<a.length;j++){var x=n.getAttribute(a[j]);if(x)return String(x);}}var raw=String(card.getAttribute&&card.getAttribute('onclick')||''),u=raw.match(/[0-9a-f]{8}-[0-9a-f-]{27,}/i);if(u)return u[0];var q=raw.match(/['\"]([^'\"]{2,100})['\"]/);return q?String(q[1]):'';}
  function idsInside(root){var f={};if(!root||!root.querySelectorAll)return [];Array.prototype.forEach.call(root.querySelectorAll(CARD_SELECTOR),function(e){var id=cardId(e);if(id)f[id]=1;});return Object.keys(f);}
  function inferZone(node){for(var c=node,d=0;c&&d<9;c=c.parentElement,d++){var z=String((c.id||'')+' '+(typeof c.className==='string'?c.className:''));if(c.getAttribute&&((c.getAttribute('data-court')!=null)||(c.getAttribute('data-court-no')!=null)||(c.getAttribute('data-court-number')!=null))||/court|코트/i.test(z))return 'court';if(c.getAttribute&&((c.getAttribute('data-wait')!=null)||(c.getAttribute('data-wait-no')!=null)||(c.getAttribute('data-wait-group')!=null))||/wait|대기/i.test(z))return 'wait';}return '';}
  function compactGroup(card){var id=cardId(card);for(var n=card&&card.parentElement,d=0;n&&d<9;n=n.parentElement,d++){var ids=idsInside(n),zone=inferZone(n);if(zone&&ids.length>=2&&ids.length<=4&&ids.indexOf(id)>=0){ids=ids.map(String).sort();return {zone:zone,ids:ids,signature:zone+'|'+ids.join('|')};}}return null;}
  function eachCardForId(id,fn){var app=document.getElementById('adminApp');if(!app)return;var seen=[];Array.prototype.forEach.call(app.querySelectorAll(CARD_SELECTOR),function(e){if(cardId(e)!==String(id))return;var c=memberCard(e)||e;if(seen.indexOf(c)<0){seen.push(c);fn(c);}});}
  function clearGreen(){var app=document.getElementById('adminApp');if(app)Array.prototype.forEach.call(app.querySelectorAll('.jm-move-selected'),function(e){e.classList.remove('jm-move-selected');});}
  function renderGreen(){clearGreen();if(moveSelection)eachCardForId(moveSelection.id,function(c){c.classList.add('jm-move-selected');});}
  function clearMove(){moveSelection=null;renderGreen();}
  function setMove(card,id){moveSelection={id:String(id),group:compactGroup(card)};renderGreen();}
  function renderYellow(){var app=document.getElementById('adminApp');if(!app)return;Array.prototype.forEach.call(app.querySelectorAll('.jm-temp-pair-v2045'),function(e){e.classList.remove('jm-temp-pair-v2045');});Object.keys(tempPairIds).forEach(function(id){if(tempPairIds[id])eachCardForId(id,function(c){c.classList.add('jm-temp-pair-v2045');});});}
  function absorb(state){tempPairIds={};var p=Array.isArray(state&&state.tempPairs)?state.tempPairs:[];p.forEach(function(g){var ids=(Array.isArray(g&&g.pairA)?g.pairA:[]).concat(Array.isArray(g&&g.pairB)?g.pairB:[]).concat(Array.isArray(g&&g.members)?g.members:[]);ids.map(String).forEach(function(id){if(id)tempPairIds[id]=1;});});renderYellow();}
  function rpc(name,args,ok,fail){var r=window.google&&window.google.script&&window.google.script.run;if(!r){if(fail)fail(new Error('서버 연결을 찾을 수 없습니다.'));return;}r.withSuccessHandler(function(x){if(ok)ok(x);}).withFailureHandler(function(e){if(fail)fail(e);})[name].apply(r,args);}
  function toast(t,bad){var o=document.getElementById('jm-admin-card-toast-v2045');if(o)o.remove();var e=document.createElement('div');e.id='jm-admin-card-toast-v2045';e.textContent=t;e.style.cssText='position:fixed;left:50%;bottom:28px;transform:translateX(-50%);z-index:2147483647;padding:10px 14px;border-radius:12px;background:'+(bad?'#991b1b':'#111827')+';color:#fff;font-size:14px;font-weight:800';document.body.appendChild(e);setTimeout(function(){e.remove();},1600);}
  function releaseNativeSelection(id){var target=null;eachCardForId(id,function(c){if(!target)target=c;});if(!target)return;nativeCleanup=true;try{target.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window}));}catch(_){}setTimeout(function(){nativeCleanup=false;clearMove();renderYellow();},0);}
  function saveTeam(first,second){rpc('getPublicState',[null],function(state){var existing=Array.isArray(state&&state.tempPairs)?state.tempPairs.slice():[];existing=existing.filter(function(p){var ids=(Array.isArray(p&&p.pairA)?p.pairA:[]).concat(Array.isArray(p&&p.pairB)?p.pairB:[]).concat(Array.isArray(p&&p.members)?p.members:[]).map(String);return ids.indexOf(first.id)<0&&ids.indexOf(second.id)<0;});existing.push({pairA:[first.id,second.id],pairB:[],zone:(first.group&&first.group.zone)||'',createdAt:Date.now()});rpc('setTempPairs',[null,existing],function(saved){tempPairIds[first.id]=1;tempPairIds[second.id]=1;clearMove();renderYellow();releaseNativeSelection(first.id);setTimeout(function(){rpc('getPublicState',[null],function(s){absorb(s);},function(){});},120);toast('같은 팀으로 설정했습니다.',false);},function(e){toast(String(e&&e.message||e||'팀 설정에 실패했습니다.'),true);});},function(e){toast(String(e&&e.message||e||'현재 팀 정보를 불러오지 못했습니다.'),true);});}
  function openDialog(first,second){if(dialogOpen)return;dialogOpen=true;var b=document.createElement('div');b.className='jm-team-confirm-backdrop';b.innerHTML='<div class="jm-team-confirm"><div class="jm-team-confirm-icon">🤝</div><div class="jm-team-confirm-title">같은 팀으로 설정할까요?</div><div class="jm-team-confirm-sub">선택한 두 사람 모두 진한 노란색 테두리로 표시됩니다.</div><div class="jm-team-confirm-actions"><button type="button" class="jm-team-no">취소</button><button type="button" class="jm-team-yes">같은 팀 설정</button></div></div>';function close(){dialogOpen=false;b.remove();}b.querySelector('.jm-team-no').onclick=function(e){e.preventDefault();e.stopPropagation();close();renderGreen();};b.querySelector('.jm-team-yes').onclick=function(e){e.preventDefault();e.stopPropagation();close();saveTeam(first,second);};document.body.appendChild(b);}
  function onClick(event){if(nativeCleanup)return;if(dialogOpen||event.button>0)return;if(event.target&&event.target.closest&&event.target.closest('.jm-team-confirm-backdrop,button,input,textarea,select,a,[role="button"]'))return;var card=memberCard(event.target);if(!card){return;}var id=cardId(card);if(!id)return;var group=compactGroup(card);if(!moveSelection){setMove(card,id);setTimeout(function(){renderGreen();renderYellow();},0);return;}if(moveSelection.id===String(id)){setTimeout(clearMove,0);return;}var first={id:moveSelection.id,group:moveSelection.group},second={id:String(id),group:group};var same=!!(first.group&&second.group&&first.group.signature===second.group.signature);if(!same&&first.group&&second.group&&first.group.zone===second.group.zone)same=first.group.ids.indexOf(second.id)>=0&&second.group.ids.indexOf(first.id)>=0;if(same){event.preventDefault();event.stopPropagation();if(event.stopImmediatePropagation)event.stopImmediatePropagation();openDialog(first,second);return;}setTimeout(clearMove,250);}
  function watch(){var app=document.getElementById('adminApp');if(!app){setTimeout(watch,120);return;}if(app.__jmV2045Observer)return;var pending=false;app.__jmV2045Observer=new MutationObserver(function(){if(pending)return;pending=true;(window.requestAnimationFrame||setTimeout)(function(){pending=false;renderGreen();renderYellow();},16);});app.__jmV2045Observer.observe(app,{childList:true,subtree:true});rpc('getPublicState',[null],function(s){absorb(s);},function(){});}
  ensureStyle();window.addEventListener('click',onClick,true);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch,{once:true});else setTimeout(watch,0);
})();
