(function installJayumintonAdminToolbarV2074(){
'use strict';
if(typeof IS_ADMIN!=='undefined'&&!IS_ADMIN)return;
if(window.__JAYUMINTON_ADMIN_TOOLBAR_V2074__)return;
window.__JAYUMINTON_ADMIN_TOOLBAR_V2074__=true;
window.__JAYUMINTON_ADMIN_TOOLBAR_V2073__=true;

function root(){return document.getElementById('adminApp');}
function selectedIds(){var ids=[];try{document.querySelectorAll('#adminApp .jm-unlimited-check').forEach(function(check){var card=check.closest('[data-member-id],[data-memberid],[data-player-id],[data-id],[data-member],.member,.person,.quick-member,.member-card,.member-item,.player-card,.court-player');if(!card)return;for(var a of ['data-member-id','data-memberid','data-player-id','data-id','data-member']){var id=String(card.getAttribute&&card.getAttribute(a)||'');if(id&&ids.indexOf(id)<0){ids.push(id);break;}}});}catch(_){}return ids;}
function toast(text,bad){var old=document.getElementById('jmV2074Toast');if(old)old.remove();var n=document.createElement('div');n.id='jmV2074Toast';n.textContent=String(text||'');n.style.cssText='position:fixed;left:50%;top:max(10px,env(safe-area-inset-top));transform:translateX(-50%);z-index:2147483647;padding:9px 13px;border-radius:11px;background:'+(bad?'#991b1b':'#111827')+';color:#fff;font-size:13px;font-weight:900;box-shadow:0 8px 24px rgba(0,0,0,.25)';document.body.appendChild(n);setTimeout(function(){n.remove();},1800);}
function messageSelected(){var ids=selectedIds();if(!ids.length)return toast('멤버를 먼저 선택하세요.',true);try{if(typeof SELECTED!=='undefined'&&SELECTED&&SELECTED.clear){SELECTED.clear();ids.forEach(function(id){SELECTED.add(String(id));});}}catch(_){}try{if(typeof window.openQuickMemberMessage==='function'){window.openQuickMemberMessage();return;}}catch(_){}var text=window.prompt('선택한 '+ids.length+'명에게 보낼 메시지를 입력하세요.','');if(!text)return;if(typeof window.server!=='function')return toast('메시지 기능을 찾을 수 없습니다.',true);window.server('sendMemberMessage',[null,ids,String(text)]).then(function(){toast(ids.length+'명에게 메시지 전송 완료');}).catch(function(e){toast(String(e&&e.message||e||'메시지 전송 실패'),true);});}
function quickCard(){var q=document.getElementById('quickSelectedCount');if(q){var c=q.closest('.card');if(c)return c;}var r=root();if(!r)return null;for(var h of r.querySelectorAll('h1,h2,h3,strong'))if(String(h.textContent||'').indexOf('빠른 코트배정')>=0)return h.closest('.card')||h.parentElement;return null;}
function quickHeader(card){if(!card)return null;return card.querySelector('.quick-roster-header')||Array.from(card.children).find(function(el){return /빠른 코트배정/.test(String(el.textContent||''));})||card.firstElementChild;}
function ensureToolbar(){var bar=document.getElementById('jmUnlimitedToolbar');if(!bar)return false;var title=bar.querySelector('.jm-u-head strong');if(title)title.textContent='멤버 팀, 교환, 메세지';var status=bar.querySelector('[data-a="status"]');if(status)status.remove();var statusSelect=bar.querySelector('#jmUnlimitedStatus');if(statusSelect)statusSelect.remove();var grid=bar.querySelector('.jm-u-grid');if(grid&&!grid.querySelector('[data-a="message"]')){var b=document.createElement('button');b.type='button';b.setAttribute('data-a','message');b.textContent='메시지보내기';var clear=grid.querySelector('[data-a="clear"]');if(clear)grid.insertBefore(b,clear);else grid.appendChild(b);b.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();messageSelected();},true);}var card=quickCard(),head=quickHeader(card);if(card){if(head&&head.parentNode===card){if(head.nextSibling!==bar)card.insertBefore(bar,head.nextSibling);}else if(bar.parentNode!==card)card.insertBefore(bar,card.firstChild);bar.classList.add('jm-toolbar-under-quick-title');}return true;}
function syncSelectionVisual(){var r=root();if(!r)return;r.querySelectorAll('.jm-v2074-selected').forEach(function(c){c.classList.remove('jm-v2074-selected');});r.querySelectorAll('.jm-unlimited-check').forEach(function(check){var card=check.closest('[data-member-id],[data-memberid],[data-player-id],[data-id],[data-member],.member,.person,.quick-member,.member-card,.member-item,.player-card,.court-player');if(card)card.classList.add('jm-v2074-selected');});}
function wait4Box(){var r=root();if(!r)return null;for(var n of r.querySelectorAll('section,.card,div')){var heads=n.querySelectorAll('h1,h2,h3,h4,strong,.title,.wait-title');for(var h of heads){if(/^대기\s*4\b/.test(String(h.textContent||'').trim()))return n;}}return null;}
function fixWait4Second(){var box=wait4Box();if(!box)return false;var list=Array.from(box.querySelectorAll('.empty,.quick-empty-slot,[class*="empty"],[onclick]')).filter(function(el){return /비어\s*있음/.test(String(el.textContent||''))||el.classList.contains('empty')||el.classList.contains('quick-empty-slot');});var slot=list[1];if(!slot)return false;slot.disabled=false;slot.removeAttribute('disabled');slot.removeAttribute('aria-disabled');slot.removeAttribute('inert');slot.classList.remove('disabled','is-disabled','inactive','non-clickable');slot.style.setProperty('pointer-events','auto','important');slot.style.setProperty('opacity','1','important');slot.style.setProperty('cursor','pointer','important');slot.setAttribute('data-jm-wait4-second-fixed','1');var raw=String(slot.getAttribute('onclick')||'');if(!/handleEmptySlotTap|handleMemberWaitEmptyTap/.test(raw))slot.setAttribute('onclick',"handleEmptySlotTap('wait','3',1)");return true;}
function installWait4Click(){var r=root();if(!r||r.__jmWait4ClickV2074)return;r.__jmWait4ClickV2074=true;r.addEventListener('click',function(e){var slot=e.target&&e.target.closest&&e.target.closest('[data-jm-wait4-second-fixed="1"]');if(!slot)return;if(typeof window.handleEmptySlotTap==='function'){e.preventDefault();e.stopImmediatePropagation();try{window.handleEmptySlotTap('wait','3',1);}catch(err){console.error(err);}}},true);}
function installStyle(){if(document.getElementById('jmToolbarV2074Style'))return;var s=document.createElement('style');s.id='jmToolbarV2074Style';s.textContent=''
+'#jmUnlimitedToolbar.jm-toolbar-under-quick-title{margin:7px 0 10px!important;padding:9px!important;border:1px solid #dbe4f0!important;border-radius:12px!important;background:#f8fafc!important;box-shadow:none!important}'
+'#jmUnlimitedToolbar .jm-u-grid{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:5px!important}'
+'#jmUnlimitedToolbar .jm-u-grid button{min-width:0!important;min-height:38px!important;padding:5px 3px!important;border-radius:9px!important;font-size:10px!important;font-weight:900!important;line-height:1.1!important;white-space:normal!important}'
+'#jmUnlimitedToolbar [data-a="all"]{background:#334155!important;border-color:#334155!important;color:#fff!important}'
+'#jmUnlimitedToolbar [data-a="active"]{background:#2563eb!important;border-color:#2563eb!important;color:#fff!important}'
+'#jmUnlimitedToolbar [data-a="perm"]{background:#7c3aed!important;border-color:#7c3aed!important;color:#fff!important}'
+'#jmUnlimitedToolbar [data-a="perm-clear"]{background:#ede9fe!important;border-color:#a78bfa!important;color:#5b21b6!important}'
+'#jmUnlimitedToolbar [data-a="temp"]{background:#d4a017!important;border-color:#b98a10!important;color:#fff!important}'
+'#jmUnlimitedToolbar [data-a="temp-clear"]{background:#fff7d6!important;border-color:#d4a017!important;color:#7a5a00!important}'
+'#jmUnlimitedToolbar [data-a="move"]{background:#059669!important;border-color:#059669!important;color:#fff!important}'
+'#jmUnlimitedToolbar [data-a="swap"]{background:#ea580c!important;border-color:#ea580c!important;color:#fff!important}'
+'#jmUnlimitedToolbar [data-a="message"]{background:#0891b2!important;border-color:#0891b2!important;color:#fff!important}'
+'#jmUnlimitedToolbar [data-a="clear"]{background:#e2e8f0!important;border-color:#cbd5e1!important;color:#334155!important}'
+'#jmUnlimitedToolbar [data-a="delete"]{background:#b91c1c!important;border-color:#b91c1c!important;color:#fff!important}'
+'#jmUnlimitedToolbar [data-a="status"],#jmUnlimitedToolbar #jmUnlimitedStatus{display:none!important}'
+'#adminApp .jm-unlimited-check{display:none!important}'
+'#adminApp .jm-v2074-selected{outline:3px solid #16a34a!important;outline-offset:2px!important;filter:brightness(.97)!important}'
+'#adminApp [data-jm-wait4-second-fixed="1"]{pointer-events:auto!important;opacity:1!important;cursor:pointer!important}'
+'@media(max-width:620px){#jmUnlimitedToolbar .jm-u-grid{grid-template-columns:repeat(3,minmax(0,1fr))!important}}';(document.head||document.documentElement).appendChild(s);}
function maintain(){ensureToolbar();fixWait4Second();syncSelectionVisual();}
function boot(){installStyle();installWait4Click();var tries=0;(function retry(){tries++;maintain();if(tries<100)setTimeout(retry,100);})();var r=root();if(r&&!r.__jmToolbarV2074Observer){var queued=false;r.__jmToolbarV2074Observer=new MutationObserver(function(){if(queued)return;queued=true;requestAnimationFrame(function(){queued=false;maintain();});});r.__jmToolbarV2074Observer.observe(r,{childList:true,subtree:true,attributes:true,attributeFilter:['class','disabled','aria-disabled','onclick']});}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else setTimeout(boot,0);
})();
