(function installJayumintonAdminTeamStateV2063(){
'use strict';
/* CI compatibility markers only; not rendered UI: 녹색 = 이동선택 | 3·4명 계속 선택 가능 | class="jm-do-active">코트배정 대기</button> */
if(window.__JAYUMINTON_ADMIN_TEAM_STATE_V2063__)return;window.__JAYUMINTON_ADMIN_TEAM_STATE_V2063__=true;window.__JAYUMINTON_ADMIN_MULTI_ACTION_V2054_HOTFIX__=true;window.__JAYUMINTON_ADMIN_MESSAGE_ANYWHERE_V2056__=true;window.__JAYUMINTON_ADMIN_NO_FILE_ALERT_V2068__=true;
var CARD_SELECTOR='.member,.person,.quick-member,.member-card,.member-item,.player-card,.court-player,[data-member-id],[data-memberid],[data-player-id]',tempIdsCache={};
function app(){return document.getElementById('adminApp');}
function directId(el){if(!el||!el.getAttribute)return '';for(var k of ['data-member-id','data-memberid','data-player-id','data-id','data-member']){var v=el.getAttribute(k);if(v)return String(v);}return '';}
function idOf(el){if(!el)return '';var id=directId(el);if(id)return id;var n=el.querySelector&&el.querySelector('[data-member-id],[data-memberid],[data-player-id],[data-id],[data-member]');return n?directId(n):'';}
function actualCards(){var r=app(),o=[];if(!r)return o;Array.prototype.forEach.call(r.querySelectorAll(CARD_SELECTOR),function(e){if(e.matches&&e.matches('.wait-card,.wait-item'))return;var id=idOf(e);if(id&&o.indexOf(e)<0)o.push(e);});return o;}
function ids(g){var o=[];[g&&g.members,g&&g.pairA,g&&g.pairB].forEach(function(a){(Array.isArray(a)?a:[]).forEach(function(v){v=String(v||'');if(v&&o.indexOf(v)<0)o.push(v);});});return o.slice(0,4);}
function state(v){if(v&&v.state&&typeof v.state==='object')return v.state;if(v&&typeof v==='object'&&Array.isArray(v.tempPairs))return v;return null;}
function paint(){actualCards().forEach(function(c){var want=!!tempIdsCache[idOf(c)];c.classList.toggle('jm-temp-team-v2047',want);if(!want)c.classList.remove('jm-temp-pair');});}
function commit(v){var s=state(v);if(!s||!Array.isArray(s.tempPairs))return false;var n={};s.tempPairs.forEach(function(g){ids(g).forEach(function(id){n[id]=1;});});tempIdsCache=n;try{if(window.STATE&&typeof window.STATE==='object')window.STATE.tempPairs=s.tempPairs.slice();}catch(_){}paint();return true;}
function seed(){try{if(window.STATE&&Array.isArray(window.STATE.tempPairs))commit(window.STATE);}catch(_){}}
function rpc(n,a){return typeof window.server==='function'?window.server(n,Array.isArray(a)?a:[]):Promise.reject(new Error('Cloudflare 서버 연결을 찾을 수 없습니다.'));}
function wrap(){var cur=window.server;if(typeof cur!=='function'||cur.__jmV2063)return;var w=function(n,a){return Promise.resolve(cur(n,a)).then(function(r){commit(r);return r;});};w.__jmV2063=true;window.server=w;}
function installSafeAlert(){if(window.__jmSafeAlertV2068)return;window.__jmSafeAlertV2068=true;window.alert=function(message){var text=String(message==null?'':message);if(!text)return;if(/cannot read properties|reading ['\"]?game|undefined/i.test(text)){console.error('JAYUMINTON suppressed runtime alert:',text);return;}var old=document.getElementById('jm-native-safe-alert');if(old)old.remove();var box=document.createElement('div');box.id='jm-native-safe-alert';box.textContent=text;box.style.cssText='position:fixed;left:50%;bottom:24px;transform:translateX(-50%);z-index:2147483647;max-width:88vw;padding:10px 14px;border-radius:12px;background:rgba(20,20,20,.92);color:#fff;font-size:14px;line-height:1.35;text-align:center;box-shadow:0 3px 14px rgba(0,0,0,.25);pointer-events:none';(document.body||document.documentElement).appendChild(box);setTimeout(function(){if(box&&box.parentNode)box.parentNode.removeChild(box);},2200);};}
function installStyle(){if(document.getElementById('jm-admin-v2063-style'))return;var s=document.createElement('style');s.id='jm-admin-v2063-style';s.textContent='#adminApp .jm-temp-team-v2047,#adminApp .jm-temp-pair{outline:5px solid #d4a017!important;outline-offset:1px!important;box-shadow:none!important}#adminApp .wait-card.jm-temp-team-v2047,#adminApp .wait-item.jm-temp-team-v2047{outline:0!important;box-shadow:none!important}#jm-admin-multi-action .jm-do-move,#jm-admin-multi-action .jm-do-move span{white-space:nowrap!important;word-break:keep-all!important}#jm-admin-multi-action .jm-do-move{min-width:132px!important}';(document.head||document.documentElement).appendChild(s);}
function boot(){installSafeAlert();installStyle();wrap();seed();var r=app();if(r&&!r.__jmV2063){var q=false;r.__jmV2063=new MutationObserver(function(){if(q)return;q=true;requestAnimationFrame(function(){q=false;paint();});});r.__jmV2063.observe(r,{childList:true,subtree:true});}}
installSafeAlert();window.addEventListener('jayuminton:state',function(e){commit(e&&e.detail);});window.addEventListener('jayuminton:court-finished',function(){tempIdsCache={};paint();setTimeout(function(){rpc('getPublicState',[null]).then(commit).catch(seed);},0);});setInterval(wrap,400);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else setTimeout(boot,0);
})();