(function installJayumintonAdminLayoutWait4CompactV2078(){
'use strict';
if(typeof IS_ADMIN!=='undefined'&&!IS_ADMIN)return;
if(window.__JAYUMINTON_ADMIN_LAYOUT_WAIT4_COMPACT_V2078__)return;
window.__JAYUMINTON_ADMIN_LAYOUT_WAIT4_COMPACT_V2078__=true;
window.__JAYUMINTON_ADMIN_LAYOUT_WAIT4_COMPACT_V2076__=true;
function root(){return document.getElementById('adminApp');}
function toast(t,b){var n=document.getElementById('jmV2078Toast');if(n)n.remove();n=document.createElement('div');n.id='jmV2078Toast';n.textContent=t;n.style.cssText='position:fixed;left:50%;top:10px;transform:translateX(-50%);z-index:2147483647;padding:8px 12px;border-radius:10px;background:'+(b?'#991b1b':'#111827')+';color:white;font-weight:900';document.body.appendChild(n);setTimeout(function(){n.remove()},1700)}
function cardId(c){if(!c)return'';for(var a of ['data-member-id','data-memberid','data-player-id','data-id','data-member']){var x=String(c.getAttribute&&c.getAttribute(a)||'');if(x)return x}var n=c.querySelector&&c.querySelector('[data-member-id],[data-memberid],[data-player-id],[data-id],[data-member]');return n?cardId(n):''}
function selectedIds(){var out=[];document.querySelectorAll('#adminApp .jm-unlimited-check').forEach(function(ch){var c=ch.closest('[data-member-id],[data-memberid],[data-player-id],[data-id],[data-member],.member,.person,.quick-member,.member-card,.member-item,.player-card,.court-player');var id=cardId(c);if(id&&out.indexOf(id)<0)out.push(id)});return out}
function quickCard(){var r=root();if(!r)return null;for(var h of r.querySelectorAll('h1,h2,h3,h4,strong,.title'))if(/빠른\s*코트배정/.test(String(h.textContent||'')))return h.closest('.card,section')||h.parentElement;return null}
function exclusionPanel(){var r=root();if(!r)return null;for(var h of r.querySelectorAll('h1,h2,h3,h4,strong,.title,summary'))if(/^코트배정\s*제외/.test(String(h.textContent||'').trim()))return h.closest('.card,section,details')||h.parentElement;return null}
function separateLayout(){var card=quickCard(),bar=document.getElementById('jmUnlimitedToolbar'),panel=exclusionPanel();if(!card||!bar)return false;var title=null;for(var h of card.querySelectorAll('h1,h2,h3,h4,strong,.title'))if(/빠른\s*코트배정/.test(String(h.textContent||''))){title=h;break}bar.style.cssText+=';position:relative!important;inset:auto!important;transform:none!important;float:none!important;clear:both!important;width:100%!important;max-width:100%!important;';if(title){var host=title.parentElement||card;if(bar.parentNode!==host||bar.previousSibling!==title)title.insertAdjacentElement('afterend',bar)}if(panel&&panel!==card&&card.parentNode&&panel.parentNode===card.parentNode&&panel.nextSibling!==card)card.parentNode.insertBefore(panel,card);return true}
function wait4Row(){var r=root();if(!r)return null;for(var n of r.querySelectorAll('div,section,.card')){var txt=String(n.textContent||'').replace(/\s+/g,'');if(txt.indexOf('대기4')===0&&txt.length<120)return n}return null}
function wait4Second(){var row=wait4Row();if(!row)return null;var slots=Array.from(row.querySelectorAll('button,.empty,.quick-empty-slot,[class*="empty"],[onclick]')).filter(function(x){return /비어\s*있음/.test(String(x.textContent||''))});return slots[0]||null}
function enableWait4(){var s=wait4Second();if(!s)return false;s.disabled=false;['disabled','aria-disabled','inert'].forEach(function(a){s.removeAttribute(a)});s.classList.remove('disabled','is-disabled','inactive','non-clickable');s.style.setProperty('pointer-events','auto','important');s.style.setProperty('opacity','1','important');s.style.setProperty('cursor','pointer','important');s.setAttribute('data-jm-v2078-wait4-slot2','1');return true}
function installWait4(){var r=root();if(!r||r.__jmV2078Wait4)return;r.__jmV2078Wait4=true;r.addEventListener('click',async function(e){var slot=e.target.closest&&e.target.closest('[data-jm-v2078-wait4-slot2="1"]');if(!slot)return;var ids=selectedIds();if(!ids.length)return;e.preventDefault();e.stopImmediatePropagation();try{if(typeof window.server!=='function')throw Error('서버 연결 없음');var ok=false,err=null;for(var call of [['assignMembersToWaitGroup',[null,3,ids]],['assignMembersToWaitGroup',[null,4,ids]]]){try{var v=await window.server(call[0],call[1]);ok=true;if(v&&typeof renderState==='function')renderState(v.state||v);break}catch(x){err=x}}if(!ok){for(var id of ids){await window.server('moveOrSwapMember',[null,String(id),'wait','3',''])}try{var f=await window.server('getPublicState',[null]);if(typeof renderState==='function')renderState(f.state||f)}catch(_){ } }toast(ids.length+'명 대기4 배정 완료')}catch(x){toast(String(x&&x.message||x||'대기4 배정 실패'),true)}},true)}
function bottom(){var r=root();if(!r)return;var move=document.getElementById('jmBottomMoveButton'),bs=Array.from(r.querySelectorAll('button'));function f(t){return bs.find(function(b){return String(b.textContent||'').trim()===t})}var undo=f('실행취소'),ref=f('새로고침'),auto=f('자동배정');if(!undo||!move||!ref||!auto)return;var p=ref.parentElement;if(undo.parentElement!==p||move.parentElement!==p||auto.parentElement!==p)return;p.classList.add('jm-v2078-bottom');[undo,move,ref,auto].forEach(function(b){b.classList.add('jm-v2078-bottom-btn');p.appendChild(b)})}
function style(){if(document.getElementById('jmV2078Style'))return;var s=document.createElement('style');s.id='jmV2078Style';s.textContent='#jmUnlimitedToolbar{position:relative!important;inset:auto!important;float:none!important;clear:both!important;width:100%!important;max-width:100%!important;margin:6px 0 10px!important;box-sizing:border-box!important}#adminApp .jm-v2078-bottom{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:4px!important;width:100%!important}#adminApp .jm-v2078-bottom-btn{min-width:0!important;width:auto!important;height:34px!important;min-height:34px!important;padding:2px!important;margin:0!important;font-size:10px!important;line-height:1!important;white-space:nowrap!important;border-radius:8px!important}#adminApp [data-jm-v2078-wait4-slot2="1"]{pointer-events:auto!important;opacity:1!important;cursor:pointer!important}@media(max-width:430px){#adminApp .jm-v2078-bottom-btn{font-size:9px!important;letter-spacing:-.5px!important}}';document.head.appendChild(s)}
function maintain(){separateLayout();enableWait4();bottom()}
function boot(){style();installWait4();var i=0;(function go(){maintain();if(++i<150)setTimeout(go,100)})();var r=root();if(r&&!r.__jmV2078Obs){var q=false;r.__jmV2078Obs=new MutationObserver(function(){if(q)return;q=true;requestAnimationFrame(function(){q=false;maintain()})});r.__jmV2078Obs.observe(r,{childList:true,subtree:true,attributes:true,attributeFilter:['class','style','disabled']})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else setTimeout(boot,0);
})();
