(function installJayumintonAdminLayoutWait4CompactV2079(){
'use strict';
if(typeof IS_ADMIN!=='undefined'&&!IS_ADMIN)return;
if(window.__JAYUMINTON_ADMIN_LAYOUT_WAIT4_COMPACT_V2079__)return;
window.__JAYUMINTON_ADMIN_LAYOUT_WAIT4_COMPACT_V2079__=true;
window.__JAYUMINTON_ADMIN_LAYOUT_WAIT4_COMPACT_V2078__=true;
window.__JAYUMINTON_ADMIN_LAYOUT_WAIT4_COMPACT_V2076__=true;
function root(){return document.getElementById('adminApp')}
function text(n){return String(n&&n.textContent||'').replace(/\s+/g,' ').trim()}
function toast(t,b){var n=document.getElementById('jmV2079Toast');if(n)n.remove();n=document.createElement('div');n.id='jmV2079Toast';n.textContent=t;n.style.cssText='position:fixed;left:50%;top:10px;transform:translateX(-50%);z-index:2147483647;padding:8px 12px;border-radius:10px;background:'+(b?'#991b1b':'#111827')+';color:white;font-weight:900';document.body.appendChild(n);setTimeout(function(){n.remove()},1700)}
function cardId(c){if(!c)return'';for(var a of ['data-member-id','data-memberid','data-player-id','data-id','data-member']){var x=String(c.getAttribute&&c.getAttribute(a)||'');if(x)return x}var n=c.querySelector&&c.querySelector('[data-member-id],[data-memberid],[data-player-id],[data-id],[data-member]');return n?cardId(n):''}
function selectedIds(){var out=[];document.querySelectorAll('#adminApp .jm-unlimited-check').forEach(function(ch){var c=ch.closest('[data-member-id],[data-memberid],[data-player-id],[data-id],[data-member],.member,.person,.quick-member,.member-card,.member-item,.player-card,.court-player');var id=cardId(c);if(id&&out.indexOf(id)<0)out.push(id)});return out}
function heading(re){var r=root();if(!r)return null;return Array.from(r.querySelectorAll('h1,h2,h3,h4,strong,.title,summary')).find(function(h){return re.test(text(h))})||null}
function quickCard(){var h=heading(/빠른\s*코트배정/);return h&&(h.closest('.card,section')||h.parentElement)}
function exclusionPanel(){var h=heading(/^코트배정\s*제외/);return h&&(h.closest('.card,section,details')||h.parentElement)}
function layout(){var card=quickCard(),bar=document.getElementById('jmUnlimitedToolbar'),panel=exclusionPanel();if(card){if(!card.classList.contains('jm-v2079-flow-card'))card.classList.add('jm-v2079-flow-card');if(panel&&panel!==card&&card.parentNode){if(!panel.classList.contains('jm-v2079-flow-panel'))panel.classList.add('jm-v2079-flow-panel');if(panel.parentNode!==card.parentNode)card.parentNode.insertBefore(panel,card);else if(panel.nextSibling!==card)card.parentNode.insertBefore(panel,card)}}if(card&&bar){var h=heading(/빠른\s*코트배정/);if(!bar.classList.contains('jm-v2079-toolbar'))bar.classList.add('jm-v2079-toolbar');if(h&&(bar.parentNode!==h.parentElement||bar.previousSibling!==h))h.insertAdjacentElement('afterend',bar)}}
function wait4Row(){var r=root();if(!r)return null;var hs=Array.from(r.querySelectorAll('h1,h2,h3,h4,strong,.title,span,div')).filter(function(n){return /^대기\s*4(?:\s|$)/.test(text(n))});for(var h of hs){var row=h.closest('.card,section,[class*="wait"],.row')||h.parentElement;if(row&&/대기\s*4/.test(text(row)))return row}return null}
function slotNodes(row){if(!row)return[];var all=Array.from(row.querySelectorAll('button,[data-slot],[data-index],[onclick],.empty,.quick-empty-slot,[class*="slot"]'));var out=[];all.forEach(function(n){if(n.closest&&n.closest('button')&&n.closest('button')!==n)return;if(/비어\s*있음/.test(text(n))||n.hasAttribute('data-slot')||n.hasAttribute('data-index')){if(out.indexOf(n)<0)out.push(n)}});return out}
function slotIndex(n,fallback){for(var a of ['data-slot-index','data-index','data-slot','data-position']){var v=n.getAttribute&&n.getAttribute(a);if(v!==null&&v!==''&&!isNaN(Number(v)))return Number(v)}var oc=String(n.getAttribute&&n.getAttribute('onclick')||'');var m=oc.match(/(?:wait|대기)[^0-9]*4[^0-9]+([0-3])/i);if(m)return Number(m[1]);return fallback}
function markWait4(){var row=wait4Row();if(!row)return;var slots=slotNodes(row);slots.forEach(function(s,i){var idx=slotIndex(s,i);s.setAttribute('data-jm-v2079-wait4-index',String(idx));s.disabled=false;['disabled','aria-disabled','inert'].forEach(function(a){s.removeAttribute(a)});if(s.classList.contains('disabled')||s.classList.contains('is-disabled')||s.classList.contains('inactive')||s.classList.contains('non-clickable'))s.classList.remove('disabled','is-disabled','inactive','non-clickable');s.style.setProperty('pointer-events','auto','important');s.style.setProperty('opacity','1','important')})}
async function assignWait4(ids){var last=null;for(var id of ids){var done=false;for(var key of ['4','3']){try{var v=await window.server('moveOrSwapMember',[null,String(id),'wait',key,'']);last=v;done=true;break}catch(e){if(!/location_full/i.test(String(e&&e.message||e)))throw e}}if(!done)throw Error('location_full')}return last}
function installWait4(){var r=root();if(!r||r.__jmV2079Wait4)return;r.__jmV2079Wait4=true;r.addEventListener('click',async function(e){var slot=e.target.closest&&e.target.closest('[data-jm-v2079-wait4-index]');if(!slot||!wait4Row()||!wait4Row().contains(slot))return;var ids=selectedIds();if(!ids.length)return;e.preventDefault();e.stopImmediatePropagation();try{if(typeof window.server!=='function')throw Error('서버 연결 없음');var v=await assignWait4(ids);if(v&&typeof renderState==='function')renderState(v.state||v);else try{var f=await window.server('getPublicState',[null]);if(typeof renderState==='function')renderState(f.state||f)}catch(_){ }toast(ids.length+'명 대기4 배정 완료')}catch(x){toast(String(x&&x.message||x||'대기4 배정 실패'),true)}},true)}
function bottom(){var r=root();if(!r)return;var bs=Array.from(r.querySelectorAll('button'));function f(t){return bs.find(function(b){return text(b)===t})}var undo=f('실행취소'),move=document.getElementById('jmBottomMoveButton')||f('자리이동'),ref=f('새로고침'),auto=f('자동배정');if(!undo||!move||!ref||!auto)return;var row=document.getElementById('jmBottomActionRowV2079');if(!row){row=document.createElement('div');row.id='jmBottomActionRowV2079';var anchor=ref.parentElement||r;anchor.parentNode.insertBefore(row,anchor.nextSibling)}
  /* Sequential idempotent reorder: appendChild() unconditionally moves a
     node even when it is already exactly where it needs to be, which fed
     this file's own MutationObserver (childList) every single cycle. Only
     move a button if it isn't immediately after the previously-placed one
     (or isn't first, for the first button) -- reconstructs the exact same
     final order [undo,move,ref,auto] as the old unconditional version, but
     is a true no-op once the row is already correctly arranged. */
  var __prevBtn=null;
  [undo,move,ref,auto].forEach(function(b){
    if(!b.classList.contains('jm-v2079-bottom-btn'))b.classList.add('jm-v2079-bottom-btn');
    var expectedPrevSibling=__prevBtn?__prevBtn.nextElementSibling:row.firstElementChild;
    if(b.parentNode!==row||expectedPrevSibling!==b)row.appendChild(b);
    __prevBtn=b;
  });
}
function badges(){/* jmBadgesIdempotentFix */var r=root();if(!r)return;Array.from(r.querySelectorAll('span,small,b,strong,em,div')).forEach(function(n){var t=text(n);if(/^신규[.!·]?$/.test(t)&&n.children.length===0){if(!n.classList.contains('jm-v2079-new-badge'))n.classList.add('jm-v2079-new-badge');var p=n.parentElement;if(p&&!p.classList.contains('jm-v2079-badge-host'))p.classList.add('jm-v2079-badge-host')}})}
function style(){if(document.getElementById('jmV2079Style'))return;var s=document.createElement('style');s.id='jmV2079Style';s.textContent='#adminApp .jm-v2079-flow-panel,#adminApp .jm-v2079-flow-card{position:relative!important;inset:auto!important;transform:none!important;float:none!important;clear:both!important;width:100%!important;max-width:100%!important;box-sizing:border-box!important}#adminApp .jm-v2079-flow-panel{margin-bottom:8px!important}#jmUnlimitedToolbar.jm-v2079-toolbar{position:relative!important;inset:auto!important;transform:none!important;float:none!important;clear:both!important;width:100%!important;max-width:100%!important;margin:6px 0 10px!important;box-sizing:border-box!important}#adminApp #jmBottomActionRowV2079{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:4px!important;width:100%!important;clear:both!important;margin:6px 0!important}#adminApp #jmBottomActionRowV2079 .jm-v2079-bottom-btn{display:block!important;min-width:0!important;width:100%!important;height:34px!important;min-height:34px!important;padding:2px!important;margin:0!important;font-size:10px!important;line-height:1!important;white-space:nowrap!important;border-radius:8px!important}#adminApp [data-jm-v2079-wait4-index]{pointer-events:auto!important;opacity:1!important;cursor:pointer!important}#adminApp .jm-v2079-new-badge{position:static!important;inset:auto!important;transform:none!important;display:inline-flex!important;vertical-align:middle!important;width:auto!important;max-width:max-content!important;min-width:0!important;height:auto!important;line-height:1.1!important;font-size:8px!important;padding:2px 3px!important;margin:0 4px 1px 0!important;z-index:auto!important;float:none!important}#adminApp .jm-v2079-badge-host{overflow:visible!important}#adminApp .jm-unlimited-check{display:none!important}@media(max-width:430px){#adminApp #jmBottomActionRowV2079 .jm-v2079-bottom-btn{font-size:9px!important;letter-spacing:-.5px!important}}';document.head.appendChild(s)}
function maintain(){layout();markWait4();bottom();badges()}
function boot(){style();installWait4();var i=0;(function go(){maintain();if(++i<180)setTimeout(go,100)})();var r=root();if(r&&!r.__jmV2079Obs){var q=false;r.__jmV2079Obs=new MutationObserver(function(){if(q)return;q=true;requestAnimationFrame(function(){q=false;maintain()})});r.__jmV2079Obs.observe(r,{childList:true,subtree:true,attributes:true,attributeFilter:['class','style','disabled']})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else setTimeout(boot,0);
})();
