#!/usr/bin/env python3
from pathlib import Path
import sys

p=Path(sys.argv[1] if len(sys.argv)>1 else 'app/src/main/assets/admin/index.html')
s=p.read_text(encoding='utf-8')
MARKER='JAYUMINTON_GAME_REPORT_POSTER_V20895'
if MARKER in s:
    print('ADMIN_GAME_REPORT_POSTER_V20895_ALREADY_OK'); raise SystemExit(0)
for token in ('JAYUMINTON_GAME_REPORT_V20893','JAYUMINTON_GAME_REPORT_RUNTIME_V20894','window.__JAYUMINTON_GAME_REPORT_V20893__','window.openPairStatistics=openPrettyGameReport'):
    if token not in s: raise SystemExit('v208.95 prerequisite missing: '+token)

STYLE=r'''
<style id="jayumintonGameReportPosterV20895Style">
/* JAYUMINTON_GAME_REPORT_POSTER_V20895 */
#pairStatisticsModal{padding:5px!important;background:rgba(2,27,39,.78)!important;backdrop-filter:blur(5px)}
#pairStatisticsModal .pair-statistics-modal{width:min(970px,99vw)!important;max-width:970px!important;max-height:96vh!important;padding:0!important;overflow:auto!important;border:0!important;border-radius:22px!important;background:#d9f7ea!important;box-shadow:0 24px 80px rgba(0,33,37,.42)!important}
#pairStatisticsModal .modal-head{display:none!important}#pairStatisticsList,#mdPairStatisticsList{padding:0!important;display:block!important;background:transparent!important}
.j95-shell{font-family:system-ui,-apple-system,'Noto Sans KR','Malgun Gothic',sans-serif;color:#092a4b;background:#d8f7e8}.j95-poster{overflow:hidden;background:linear-gradient(180deg,#b9ebff 0,#dff9ee 39%,#d5f6e2 100%)}
.j95-hero{position:relative;overflow:hidden;padding:24px 30px 24px;background:radial-gradient(circle at 9% 8%,#fff 0 5%,transparent 20%),radial-gradient(circle at 70% 5%,rgba(255,255,255,.75) 0 7%,transparent 25%),radial-gradient(circle at 92% 14%,rgba(255,255,255,.78) 0 7%,transparent 23%),linear-gradient(180deg,#9fddff 0,#d9f5ff 56%,#aaf1c1 100%)}
.j95-hero:before{content:'';position:absolute;left:-6%;right:-6%;bottom:-25px;height:210px;background:repeating-linear-gradient(0deg,rgba(0,157,107,.13) 0 2px,transparent 2px 37px),repeating-linear-gradient(90deg,rgba(0,157,107,.11) 0 2px,transparent 2px 58px);transform:skewY(-4deg)}
.j95-hero:after{content:'';position:absolute;left:58%;right:-8%;bottom:96px;height:92px;border-top:4px solid rgba(0,131,96,.38);border-bottom:4px solid rgba(0,131,96,.24);transform:rotate(-6deg)}
.j95-noteL,.j95-noteR,.j95-motto{position:absolute;z-index:3;font-family:cursive;font-weight:850;line-height:1.35}.j95-noteL{left:4%;top:5%;font-size:clamp(10px,1.6vw,18px);transform:rotate(-9deg);color:#112f3d}.j95-noteR{right:3%;top:4%;font-size:clamp(9px,1.4vw,15px);text-align:center;transform:rotate(8deg);color:#5b6de4}.j95-motto{left:5%;top:27%;font-family:system-ui;font-size:clamp(8px,1.15vw,12px);letter-spacing:.27em;line-height:1.45;color:#6874da}
.j95-brand{position:relative;z-index:3;text-align:center;margin-top:10px;font-size:clamp(55px,9.5vw,103px);line-height:.92;font-weight:1000;letter-spacing:-.095em;color:#fff;text-shadow:0 4px 0 #c6f7e2,0 7px 0 #35d99b,0 10px 0 #07537c,0 14px 18px rgba(2,56,92,.35)}.j95-brand b{color:#a8ffd1}.j95-sub{position:relative;z-index:3;margin-top:18px;text-align:center;font-size:clamp(30px,5.3vw,56px);font-weight:1000;letter-spacing:-.06em;color:#092b54}.j95-cap{position:relative;z-index:3;margin-top:6px;text-align:center;font-size:clamp(12px,2vw,21px);font-weight:850;color:#3948b3}
.j95-date{position:relative;z-index:4;width:max-content;max-width:76%;margin:15px auto 20px;padding:8px 22px;border-radius:999px;background:rgba(249,253,255,.94);font-size:clamp(12px,1.8vw,19px);font-weight:850;color:#173b72;box-shadow:0 5px 17px rgba(6,62,88,.11)}
.j95-dog{position:absolute;z-index:4;right:7%;top:19%;width:12%;min-width:70px}.j95-dog svg{width:100%;height:auto;display:block;filter:drop-shadow(0 4px 2px rgba(0,0,0,.09))}.j95-shuttle{position:absolute;z-index:4;font-size:clamp(25px,4vw,43px)}.j95-shuttle.a{left:50%;top:1%;transform:rotate(18deg)}.j95-shuttle.b{right:22%;top:16%;transform:rotate(-18deg)}
.j95-sum{position:relative;z-index:5;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.j95-card{min-height:148px;padding:20px 17px;border-radius:23px;background:rgba(255,255,255,.97);box-shadow:0 10px 25px rgba(10,116,91,.13)}.j95-card small{display:block;color:#086de7;font-size:clamp(11px,1.5vw,17px);font-weight:950}.j95-card strong{display:block;margin-top:15px;color:#071f4c;font-size:clamp(29px,4.7vw,52px);line-height:1;font-weight:1000;letter-spacing:-.055em}.j95-card strong em{font-size:.48em;font-style:normal;margin-left:3px}
.j95-body{padding:0 3.2% 26px;background:linear-gradient(180deg,rgba(183,255,214,.5),rgba(235,255,246,.72))}.j95-panel{margin-bottom:22px;overflow:hidden;border:2px solid rgba(0,200,135,.48);border-radius:24px;background:rgba(255,255,255,.93);box-shadow:0 12px 28px rgba(0,104,77,.13)}.j95-head{min-height:74px;padding:15px 22px;display:flex;align-items:center;justify-content:space-between;gap:14px;color:#fff;background:linear-gradient(120deg,#006b72,#00865f)}.j95-head strong{font-size:clamp(22px,3.2vw,38px);font-weight:1000}.j95-head span{font-size:clamp(9px,1.3vw,15px);font-weight:760;color:#e1fff5;text-align:right}
.j95-th,.j95-row{display:grid;grid-template-columns:minmax(145px,1.15fr) 92px 110px 110px minmax(265px,2.05fr);gap:8px;align-items:center}.j95-th{min-height:50px;padding:0 17px;background:linear-gradient(#edf8ff,#eaf4f8);color:#4c8799;font-size:12px;font-weight:950;text-align:center}.j95-row{min-height:69px;padding:8px 17px;border-top:1px solid #e3edf0;background:rgba(255,255,255,.87)}.j95-row:nth-child(even){background:#f9fdfc}.j95-name{display:flex;align-items:center;gap:11px;font-size:17px;font-weight:1000}.j95-av{flex:0 0 auto;width:42px;height:42px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:18px;font-weight:1000;background:var(--bg);color:var(--fg)}.j95-games{text-align:center;color:#00ac67;font-size:20px;font-weight:1000}.j95-time{text-align:center;color:#345eb0;font-size:16px;font-weight:820;white-space:nowrap}.j95-partners{font-size:13px;line-height:1.5;color:#2d5aa0;font-weight:720}.j95-chip{display:inline-flex;margin:2px 3px 2px 0;padding:4px 7px;border-radius:999px;background:#eef6ff;border:1px solid #d8e8ff;white-space:nowrap}.j95-chip b{margin-left:3px;color:#0b8068}.j95-more{background:#fff7d9;border-color:#f1dc80;color:#8a6400;cursor:pointer}.j95-empty{color:#94a5ac}
.j95-hi{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;padding:15px}.j95-hc{min-height:150px;padding:17px;border-radius:22px;background:linear-gradient(145deg,#f4fff8,#e8fff3);border:1px solid #d3f0dd}.j95-hc:nth-child(2){background:linear-gradient(145deg,#eef9ff,#e0f1ff)}.j95-hc:nth-child(3){background:linear-gradient(145deg,#fff8ef,#ffefe2)}.j95-hc small{font-size:13px;font-weight:950;color:#08705b}.j95-hc strong{display:block;margin-top:11px;font-size:clamp(21px,3vw,33px);font-weight:1000;color:#08294b}.j95-hc em{display:block;margin-top:5px;font-size:clamp(18px,2.5vw,29px);font-style:normal;font-weight:1000;color:#00ad6a}
.j95-footer{position:relative;min-height:170px;background:linear-gradient(180deg,rgba(237,255,245,.6),rgba(49,217,189,.5)),repeating-linear-gradient(90deg,transparent 0 105px,rgba(0,126,104,.17) 106px 108px),repeating-linear-gradient(0deg,transparent 0 58px,rgba(0,126,104,.15) 59px 61px)}.j95-footer:before{content:'자유민턴  |  코트 위의 더 즐거운 시간 기록';position:absolute;left:4%;top:26px;font-size:clamp(11px,1.5vw,17px);font-weight:850;color:#143d55}.j95-footer:after{content:'—  BADMINTON MAKES A BRIGHTER TOMORROW  —';position:absolute;left:0;right:0;bottom:24px;text-align:center;color:#eefefa;font-size:10px;letter-spacing:.33em;font-weight:800}.j95-footer .j95-dog{top:auto;right:7%;bottom:3px;width:82px;min-width:0}
.j95-actions{position:sticky;bottom:0;z-index:12;display:flex;justify-content:center;gap:10px;padding:12px 14px;background:linear-gradient(180deg,rgba(218,248,234,.2),rgba(218,248,234,.98) 32%)}.j95-save,.j95-close{min-height:47px;padding:0 21px;border-radius:15px;font-size:15px;font-weight:1000}.j95-save{border:0;background:linear-gradient(135deg,#00a96c,#00c47e);color:white;box-shadow:0 8px 18px rgba(0,169,108,.24)}.j95-close{border:1px solid #c9ddd6;background:white;color:#355a52}
@media(max-width:720px){.j95-hero{padding:17px 10px 15px}.j95-dog{right:3%;top:21%;min-width:56px}.j95-sum{gap:6px}.j95-card{min-height:108px;padding:12px 8px;border-radius:15px}.j95-card strong{margin-top:8px}.j95-panel{border-radius:15px;margin-bottom:14px}.j95-head{min-height:55px;padding:10px 11px}.j95-th,.j95-row{grid-template-columns:minmax(88px,1.1fr) 52px 63px 63px minmax(145px,1.8fr);gap:3px;padding-left:7px;padding-right:7px}.j95-th{min-height:37px;font-size:9px}.j95-row{min-height:56px}.j95-name{gap:5px;font-size:11px}.j95-av{width:28px;height:28px;font-size:12px}.j95-games{font-size:13px}.j95-time{font-size:10px}.j95-partners{font-size:9px}.j95-chip{padding:2px 4px}.j95-hc{min-height:108px;padding:10px}.j95-hc small{font-size:9px}.j95-footer{min-height:115px}.j95-save,.j95-close{min-height:41px;font-size:13px}}
</style>
'''
SCRIPT=r'''
<script id="jayumintonGameReportPosterV20895Script">
/* JAYUMINTON_GAME_REPORT_POSTER_V20895 */
(function(){'use strict';
var COLORS=[['#e4ecff','#245fd7'],['#ffe2eb','#dd3e74'],['#e2f3ed','#173f49'],['#ece3ff','#6534d8'],['#ffefcf','#b77600'],['#dff2ff','#1680d6']];
function e(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}function src(){return Array.isArray(window.ADMIN_PAIR_STATISTICS)?window.ADMIN_PAIR_STATISTICS:(Array.isArray(window.MD_PAIR_STATISTICS)?window.MD_PAIR_STATISTICS:[]);}function rows(){return src().slice().sort(function(a,b){return Number(b.games||0)-Number(a.games||0)||String(a.name||'').localeCompare(String(b.name||''),'ko');});}function d(v){var x=v?new Date(String(v)):null;return x&&!Number.isNaN(x.getTime())?x:null;}function hm(v){var x=d(v);if(!x)return '-';try{var p=new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(x),h=(p.find(function(q){return q.type==='hour';})||{}).value,m=(p.find(function(q){return q.type==='minute';})||{}).value;return h&&m?h+':'+m:'-';}catch(_){return '-';}}function day(){try{return new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit',weekday:'long'}).format(new Date());}catch(_){return new Date().toLocaleDateString('ko-KR');}}function dur(ms){if(!Number.isFinite(ms)||ms<0)return '-';var m=Math.round(ms/60000);return Math.floor(m/60)+'시간 '+m%60+'분';}function courts(){return 4;}
function stats(a){var attendees=a.filter(function(r){return r.arrivedAt||Number(r.games||0)>0;}),total=a.reduce(function(s,r){return s+Math.max(0,Number(r.games||0));},0),starts=a.map(function(r){return d(r.arrivedAt);}).filter(Boolean).sort(function(x,y){return x-y;}),ends=a.map(function(r){return d(r.departedAt);}).filter(Boolean).sort(function(x,y){return x-y;}),active=a.some(function(r){return r.arrivedAt&&!r.departedAt;}),max=a.slice().sort(function(x,y){return Number(y.games||0)-Number(x.games||0);})[0]||null,now=Date.now(),long=null,longMs=-1,seen=new Set(),pair=null;a.forEach(function(r){var x=d(r.arrivedAt);if(!x)return;var y=d(r.departedAt)||new Date(now),ms=y-x;if(ms>longMs){long=r;longMs=ms;}});a.forEach(function(r){(r.partners||[]).forEach(function(p){var x=String(r.id||r.name),y=String(p.id||p.name),key=[x,y].sort().join('::');if(seen.has(key))return;seen.add(key);var n=Number(p.count||0);if(!pair||n>pair.count)pair={a:r.name,b:p.name,count:n};});});return{attendees:attendees.length,total:total,matches:Math.max(0,Math.round(total/4)),avg:attendees.length?total/attendees.length:0,start:starts[0]||null,end:active?new Date():(ends.length?ends[ends.length-1]:null),courts:courts(),max:max,long:long,longMs:longMs,pair:pair};}
function dog(cls){return '<div class="'+cls+'"><svg viewBox="0 0 130 130"><path d="M35 31c-9-10-18-10-22-3-4 8 4 18 15 17-5 11-7 26-4 39 4 21 17 33 40 34 24 1 39-12 43-33 3-14 1-29-5-40 11 1 19-9 15-17-4-7-13-7-22 3-16-7-43-7-60 0z" fill="#fff" stroke="#111820" stroke-width="4.5" stroke-linejoin="round"/><circle cx="52" cy="61" r="3.2"/><circle cx="76" cy="61" r="3.2"/><path d="M60 68c2-3 5-3 7 0M54 73c5 7 14 7 19 0" fill="none" stroke="#111820" stroke-width="3.8" stroke-linecap="round"/><path d="M60 77c3 9 10 9 13 0-5 2-9 2-13 0z" fill="#ff6b72" stroke="#111820" stroke-width="2.7"/></svg></div>';}
function av(name,i){var c=COLORS[i%COLORS.length],x=String(name||'?').trim().charAt(0)||'?';return '<span class="j95-av" style="--bg:'+c[0]+';--fg:'+c[1]+'">'+e(x)+'</span>';}function compact(r,n){var p=r.partners||[],s=p.slice(0,n||4),t=s.map(function(x){return String(x.name||'')+(Number(x.count||0)>1?' '+Number(x.count||0)+'회':'');}).join(', ');if(p.length>s.length)t+=(t?', ':'')+'외 '+(p.length-s.length)+'명';return t||'기록 없음';}function ph(r){var p=r.partners||[],s=p.slice(0,4),m=p.length-s.length,h=s.map(function(x){return '<span class="j95-chip">'+e(x.name)+(Number(x.count||0)>1?' <b>'+Number(x.count||0)+'회</b>':'')+'</span>';}).join('');if(m>0)h+='<span class="j95-chip j95-more" data-id="'+e(r.id||r.name)+'">외 '+m+'명</span>';return h||'<span class="j95-empty">기록 없음</span>';}function card(label,v,u){return '<div class="j95-card"><small>'+label+'</small><strong>'+e(v)+'<em>'+u+'</em></strong></div>';}
function render(){var t=document.getElementById('pairStatisticsList')||document.getElementById('mdPairStatisticsList');if(!t)return;var a=rows(),s=stats(a),body=a.map(function(r,i){return '<div class="j95-row"><div class="j95-name">'+av(r.name,i)+'<span>'+e(r.name)+'</span></div><div class="j95-games">'+Number(r.games||0)+'회</div><div class="j95-time">'+hm(r.arrivedAt)+'</div><div class="j95-time">'+hm(r.departedAt)+'</div><div class="j95-partners" data-export="'+e(compact(r,6))+'">'+ph(r)+'</div></div>';}).join('')||'<div style="padding:42px;text-align:center;font-weight:900">표시할 통계가 없습니다.</div>',max=s.max?e(s.max.name):'-',maxN=s.max?Number(s.max.games||0)+'회':'-',ln=s.long?e(s.long.name):'-',ld=s.long?dur(s.longMs):'-',pn=s.pair?e(s.pair.a)+' · '+e(s.pair.b):'-',pc=s.pair?s.pair.count+'회':'-';t.innerHTML='<div class="j95-shell"><div class="j95-poster" id="j95Poster" data-jm-poster="208.95"><section class="j95-hero"><div class="j95-noteL">좋은 사람들과<br>오늘도<br><b>자유롭게!</b></div><div class="j95-noteR">Badminton<br>More Than<br>A Game! ♡</div><div class="j95-motto">GOOD<br>PLAYERS<br>BETTER<br>DAYS</div><span class="j95-shuttle a">🏸</span><span class="j95-shuttle b">🏸</span><div class="j95-brand">자유<b>민턴</b></div><div class="j95-sub">오늘의 게임 통계</div><div class="j95-cap">게임 종료 후 한눈에 보는 요약 리포트</div><div class="j95-date">▣ '+e(day())+' · '+hm(s.start)+'~'+hm(s.end)+'</div>'+dog('j95-dog')+'<div class="j95-sum">'+card('👥 총 참석',s.attendees,'명')+card('🏸 총 경기',s.matches,'게임')+card('▦ 사용 코트',s.courts||'-','면')+card('▥ 평균 게임',s.avg.toFixed(1),'회')+'</div></section><main class="j95-body"><section class="j95-panel"><div class="j95-head"><strong>👥 참여자 통계</strong><span>오늘도 좋은 게임, 좋은 사람들<br>자유민턴♡</span></div><div class="j95-th"><span>이름</span><span>총 게임</span><span>도착</span><span>귀가</span><span>함께 경기한 사람</span></div>'+body+'</section><section class="j95-panel"><div class="j95-head"><strong>🏆 오늘의 하이라이트</strong><span>다음엔 왠지 오늘보다<br>더 특별한 하루♡</span></div><div class="j95-hi"><div class="j95-hc"><small>♛ 최다 경기</small><strong>'+max+'</strong><em>'+maxN+'</em></div><div class="j95-hc"><small>◷ 최장 참여</small><strong>'+ln+'</strong><em>'+ld+'</em></div><div class="j95-hc"><small>👥 인기 파트너</small><strong>'+pn+'</strong><em>'+pc+'</em></div></div></section></main><footer class="j95-footer">'+dog('j95-dog')+'</footer></div><div class="j95-actions"><button class="j95-save" onclick="window.jmSaveGameReportImage()">📷 전체 이미지 저장</button><button class="j95-close" onclick="closePairStatistics()">닫기</button></div></div>';}
function save(){var p=document.getElementById('j95Poster');if(!p){alert('저장할 통계 화면이 없습니다.');return;}var c=p.cloneNode(true);c.querySelectorAll('.j95-partners').forEach(function(x){x.textContent=x.getAttribute('data-export')||'기록 없음';});var host=document.createElement('div');host.style.cssText='position:fixed;left:-12000px;top:0;width:941px;z-index:-1';c.style.width='941px';host.appendChild(c);document.body.appendChild(host);requestAnimationFrame(function(){requestAnimationFrame(function(){try{var w=941,h=Math.max(600,Math.ceil(c.scrollHeight)),css=document.getElementById('jayumintonGameReportPosterV20895Style').textContent,markup='<div xmlns="http://www.w3.org/1999/xhtml"><style>'+css+'</style>'+c.outerHTML+'</div>',svg='<svg xmlns="http://www.w3.org/2000/svg" width="'+w+'" height="'+h+'"><foreignObject width="100%" height="100%">'+markup+'</foreignObject></svg>',blob=new Blob([svg],{type:'image/svg+xml;charset=utf-8'}),url=URL.createObjectURL(blob),im=new Image();im.onload=function(){var cv=document.createElement('canvas');cv.width=w;cv.height=h;var ctx=cv.getContext('2d');ctx.fillStyle='#d8f7e8';ctx.fillRect(0,0,w,h);ctx.drawImage(im,0,0);URL.revokeObjectURL(url);host.remove();var data=cv.toDataURL('image/png'),name='자유민턴_게임통계_'+new Date().toISOString().slice(0,10)+'.png';if(window.NativeBrowser&&typeof window.NativeBrowser.saveStatisticsPng==='function')window.NativeBrowser.saveStatisticsPng(data,name);else{var a=document.createElement('a');a.href=data;a.download=name;a.click();}};im.onerror=function(){URL.revokeObjectURL(url);host.remove();alert('전체 이미지를 만들지 못했습니다.');};im.src=url;}catch(err){host.remove();alert('전체 이미지 저장 실패: '+(err.message||err));}});});}
document.addEventListener('click',function(ev){var m=ev.target&&ev.target.closest?ev.target.closest('.j95-more'):null;if(!m)return;var box=m.closest('.j95-partners'),id=m.getAttribute('data-id'),r=rows().find(function(x){return String(x.id||x.name)===String(id);});if(!box||!r)return;if(String(m.textContent||'').trim()==='접기'){box.innerHTML=ph(r);return;}box.innerHTML=(r.partners||[]).map(function(x){return '<span class="j95-chip">'+e(x.name)+(Number(x.count||0)>1?' <b>'+Number(x.count||0)+'회</b>':'')+'</span>';}).join('')+'<span class="j95-chip j95-more" data-id="'+e(r.id||r.name)+'">접기</span>';});
function install(){var api=window.__JAYUMINTON_GAME_REPORT_V20893__;if(!api)return;api.render=render;api.svg=function(){return'';};window.renderPairStatistics=render;window.renderMdPairStatistics=render;window.jmSaveGameReportImage=save;window.__JAYUMINTON_GAME_REPORT_V20895__={render:render,save:save,stats:stats};}install();if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});setTimeout(install,0);setTimeout(install,450);setTimeout(install,1200);})();
</script>
'''
if '</head>' not in s or '</body>' not in s: raise SystemExit('HTML anchors missing')
s=s.replace('</head>',STYLE+'\n</head>',1).replace('</body>',SCRIPT+'\n</body>',1)
for token in (MARKER,'data-jm-poster="208.95"','자유<b>민턴</b>','👥 참여자 통계','🏆 오늘의 하이라이트','총 참석','총 경기','사용 코트','평균 게임','전체 이미지 저장','window.jmSaveGameReportImage=save','api.render=render','<foreignObject'):
    if token not in s: raise SystemExit('v208.95 poster contract missing: '+token)
p.write_text(s,encoding='utf-8')
print('ADMIN_GAME_REPORT_POSTER_V20895_OK')
