(function installJayumintonAdminMultiActionV2053(){
  'use strict';
  if(typeof IS_ADMIN==='undefined'||!IS_ADMIN||window.__JAYUMINTON_ADMIN_MULTI_ACTION_V2053__)return;
  window.__JAYUMINTON_ADMIN_MULTI_ACTION_V2047__=true;
  window.__JAYUMINTON_ADMIN_MULTI_ACTION_V2052__=true;
  window.__JAYUMINTON_ADMIN_MULTI_ACTION_V2053__=true;
  window.__JAYUMINTON_ADMIN_TEAM_VISUAL_STABLE_V2055__=true;

  var CARD_SELECTOR='.member,.person,.quick-member,.member-card,.member-item,.wait-card,.wait-item,.player-card,.court-player,[data-member-id],[data-memberid],[data-player-id]';
  var DIRECT_ID_SELECTOR='[data-member-id],[data-memberid],[data-player-id],[data-id],[data-member]';
  var selected=[],group=null,phase='source',targets=[],targetKind='',yellow={};

  function app(){return document.getElementById('adminApp');}
  function ensureStyle(){
    var old=document.getElementById('jayuminton-admin-team-safety-v2037');if(old)old.remove();
    if(document.getElementById('jayuminton-admin-multi-action-v2053-style'))return;
    var s=document.createElement('style');s.id='jayuminton-admin-multi-action-v2053-style';
    s.textContent=''
      +'#adminApp .jm-source-selected,#adminApp .jm-target-selected{box-shadow:0 0 0 4px #16a34a!important;outline:2px solid rgba(22,163,74,.22)!important;outline-offset:1px!important}'
      +'#adminApp .jm-temp-team-v2047,#adminApp .jm-temp-pair{box-shadow:0 0 0 4px #d4a017!important;outline:2px solid rgba(212,160,23,.24)!important;outline-offset:1px!important}'
      +'.jm-multi-action{position:fixed;left:50%;bottom:18px;transform:translateX(-50%);z-index:2147483645;width:min(540px,calc(100vw - 16px));background:#fff;border:1px solid #e2e8f0;border-radius:20px;padding:12px;box-shadow:0 18px 55px rgba(15,23,42,.28);font-family:inherit}'
      +'.jm-multi-head{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-bottom:8px}.jm-multi-title{font-size:15px;font-weight:900;color:#111827}.jm-multi-count{font-size:12px;font-weight:800;color:#15803d;background:#f0fdf4;border-radius:999px;padding:5px 8px;white-space:nowrap}.jm-multi-help{font-size:12px;color:#64748b;line-height:1.4;margin-bottom:9px}.jm-multi-actions{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.jm-multi-action button{border:0;border-radius:12px;min-width:0;min-height:44px;font-size:13px;font-weight:850;font-family:inherit;white-space:nowrap!important;word-break:keep-all!important;overflow-wrap:normal!important;padding:0 7px;line-height:1!important}.jm-do-move{background:#dcfce7;color:#166534}.jm-do-active{background:#dbeafe;color:#1d4ed8}.jm-do-team{background:#d4a017;color:#fff}.jm-do-cancel{background:#f1f5f9;color:#475569}.jm-do-team:disabled{opacity:.38}';
    (document.head||document.documentElement).appendChild(s);
  }
  function directId(e){if(!e||!e.getAttribute)return '';var a=['data-member-id','data-memberid','data-player-id','data-id','data-member'];for(var i=0;i<a.length;i++){var v=e.getAttribute(a[i]);if(v)return String(v);}return '';}
  function idOf(c){if(!c)return '';var v=directId(c);if(v)return v;var raw=String(c.getAttribute&&c.getAttribute('onclick')||''),m=raw.match(/[0-9a-f]{8}-[0-9a-f-]{27,}/i);return m?m[0]:'';}
  function card(target){if(!target||!target.closest)return null;var c=target.closest(DIRECT_ID_SELECTOR);if(c&&c.closest('#adminApp')&&!c.classList.contains('empty')&&!c.classList.contains('quick-empty-slot'))return c;c=target.closest(CARD_SELECTOR);if(!c||!c.closest('#adminApp')||c.classList.contains('empty')||c.classList.contains('quick-empty-slot'))return null;return idOf(c)?c:null;}
  function each(id,fn){var a=app();if(!a)return;var seen=[];Array.prototype.forEach.call(a.querySelectorAll(DIRECT_ID_SELECTOR),function(e){if(directId(e)!==String(id))return;var c=e;if(seen.indexOf(c)<0){seen.push(c);fn(c);}});if(seen.length)return;Array.prototype.forEach.call(a.querySelectorAll(CARD_SELECTOR),function(e){if(idOf(e)!==String(id))return;if(seen.indexOf(e)<0){seen.push(e);fn(e);}});}
  function clearClass(name){var a=app();if(a)Array.prototype.forEach.call(a.querySelectorAll('.'+name),function(e){e.classList.remove(name);});}
  function renderGreen(){clearClass('jm-source-selected');clearClass('jm-target-selected');selected.forEach(function(id){each(id,function(c){c.classList.add('jm-source-selected');});});targets.forEach(function(t){if(t.kind==='member')each(t.id,function(c){c.classList.add('jm-target-selected');});else if(t.el&&document.contains(t.el))t.el.classList.add('jm-target-selected');});}
  function tempIds(p){var a=[];[p&&p.members,p&&p.pairA,p&&p.pairB].forEach(function(v){(Array.isArray(v)?v:[]).forEach(function(x){x=String(x||'');if(x&&a.indexOf(x)<0)a.push(x);});});return a.slice(0,4);}
  function absorb(state){if(!Array.isArray(state&&state.tempPairs))return;var next={};state.tempPairs.forEach(function(p){tempIds(p).forEach(function(id){next[id]=1;});});yellow=next;renderYellow();}
  function renderYellow(){var a=app();if(!a)return;Array.prototype.forEach.call(a.querySelectorAll('.jm-temp-team-v2047,.jm-temp-pair'),function(e){var id=idOf(e);if(!id||!yellow[String(id)]){e.classList.remove('jm-temp-team-v2047');e.classList.remove('jm-temp-pair');}});Object.keys(yellow).forEach(function(id){if(yellow[id])each(id,function(c){if(!c.classList.contains('jm-temp-team-v2047'))c.classList.add('jm-temp-team-v2047');});});}
  function rpc(name,args){if(typeof window.server!=='function')return Promise.reject(new Error('Cloudflare 서버 연결을 찾을 수 없습니다.'));return window.server(String(name||''),Array.isArray(args)?args:[]);}
  function toast(t,bad){var o=document.getElementById('jm-admin-multi-toast');if(o)o.remove();var e=document.createElement('div');e.id='jm-admin-multi-toast';e.textContent=String(t||'');e.style.cssText='position:fixed;left:50%;bottom:92px;transform:translateX(-50%);z-index:2147483647;padding:10px 14px;border-radius:12px;background:'+(bad?'#991b1b':'#111827')+';color:#fff;font-size:14px;font-weight:800;box-shadow:0 8px 26px rgba(0,0,0,.22)';document.body.appendChild(e);setTimeout(function(){e.remove();},1800);}
  function state(){try{return typeof STATE!=='undefined'?STATE:null;}catch(_){return null;}}
  function locate(id){var st=state();if(!st)return null;var cs=st.courts||{};for(var k in cs)if(Array.isArray(cs[k])&&cs[k].map(String).indexOf(String(id))>=0)return {type:'court',key:String(k)};var ws=st.waitGroups||[];for(var i=0;i<ws.length;i++)if(Array.isArray(ws[i])&&ws[i].map(String).indexOf(String(id))>=0)return {type:'wait',key:String(i+1)};return null;}
  function signature(id){var l=locate(id);return l?l.type+'|'+l.key:'';}
  function samePlace(ids){if(!ids.length)return true;var s=signature(ids[0]);return !!s&&ids.every(function(id){return signature(id)===s;});}
  function clearMessageSelection(){
    try{if(typeof SELECTED!=='undefined'&&SELECTED&&typeof SELECTED.clear==='function')SELECTED.clear();}catch(e){}
    var a=app();if(a)Array.prototype.forEach.call(a.querySelectorAll('.selected,.quick-picked'),function(c){c.classList.remove('selected','quick-picked');});
    var quick=document.getElementById('quickSelectedCount'),mobile=document.getElementById('mobileSelectedCount'),bulk=document.getElementById('mdBulkDeleteCount'),del=document.getElementById('mdBulkDeleteButton');
    if(quick){quick.textContent='0명 선택';quick.classList.remove('has-selection');}if(mobile)mobile.textContent='0명 선택';if(bulk)bulk.textContent='0명 선택';if(del)del.disabled=true;
  }
  function reset(skipYellow,keepMessageSelection){selected=[];group=null;phase='source';targets=[];targetKind='';if(!keepMessageSelection)clearMessageSelection();renderGreen();renderPanel();if(!skipYellow)renderYellow();}
  window.__JAYUMINTON_RESET_MULTI_SELECTION_V2057__=function(){reset(false,true);};
  function panel(){var p=document.getElementById('jm-admin-multi-action');if(!p){p=document.createElement('div');p.id='jm-admin-multi-action';p.className='jm-multi-action';document.body.appendChild(p);}return p;}
  function renderPanel(){var p=document.getElementById('jm-admin-multi-action');if(!selected.length){if(p)p.remove();return;}if(phase==='target'){p=panel();p.innerHTML='<div class="jm-multi-head"><div class="jm-multi-title">'+selected.length+'명 이동/교환</div><div class="jm-multi-count">대상 '+targets.length+'/'+selected.length+'</div></div><div class="jm-multi-help">빈자리 '+selected.length+'곳 또는 바꿀 사람 '+selected.length+'명을 선택하세요.</div><div class="jm-multi-actions" style="grid-template-columns:1fr 90px"><button type="button" class="jm-back-source">사람 다시 선택</button><button type="button" class="jm-do-cancel">취소</button></div>';p.querySelector('.jm-back-source').onclick=function(e){e.stopPropagation();phase='source';targets=[];targetKind='';renderGreen();renderPanel();};p.querySelector('.jm-do-cancel').onclick=function(e){e.stopPropagation();reset();};return;}if(selected.length!==2){if(p)p.remove();return;}var canTeam=samePlace(selected);p=panel();p.innerHTML='<div class="jm-multi-head"><div class="jm-multi-title">2명 선택</div><div class="jm-multi-count">녹색 = 이동선택</div></div><div class="jm-multi-help">이동/교환, 코트배정 대기 또는 팀설정을 선택하세요. 1명·3명·4명은 자동으로 이동/교환입니다.</div><div class="jm-multi-actions"><button type="button" class="jm-do-move">이동/교환</button><button type="button" class="jm-do-active">코트배정 대기</button><button type="button" class="jm-do-team" '+(canTeam?'':'disabled')+'>팀설정</button><button type="button" class="jm-do-cancel">취소</button></div>';p.querySelector('.jm-do-move').onclick=function(e){e.stopPropagation();phase='target';targets=[];targetKind='';renderPanel();};p.querySelector('.jm-do-active').onclick=function(e){e.stopPropagation();moveSelectedToActive(selected.slice());};p.querySelector('.jm-do-team').onclick=function(e){e.stopPropagation();if(canTeam)saveTeam(selected.slice());};p.querySelector('.jm-do-cancel').onclick=function(e){e.stopPropagation();reset();};}
  async function moveSelectedToActive(ids){ids=(Array.isArray(ids)?ids:[]).map(String).filter(Boolean);try{if(ids.length!==2||!samePlace(ids))throw new Error('같은 대기번호 또는 같은 코트의 2명을 선택해 주세요.');var p=document.getElementById('jm-admin-multi-action');if(p)Array.prototype.forEach.call(p.querySelectorAll('button'),function(button){button.disabled=true;});var saved=await rpc('setMemberStatus',[null,ids,'active']);reset();if(typeof renderState==='function')renderState(saved);toast(ids.length+'명 코트배정 대기로 이동 완료',false);}catch(e){renderPanel();toast(String(e&&e.message||e||'코트배정 대기 이동 실패'),true);}}
  async function saveTeam(ids){var before=Object.assign({},yellow);try{if(ids.length!==2)throw new Error('팀설정은 2명 선택일 때만 사용할 수 있습니다.');var loc=locate(ids[0]);if(!loc||!samePlace(ids))throw new Error('같은 대기번호 또는 같은 코트의 2명만 팀설정할 수 있습니다.');ids.forEach(function(id){yellow[String(id)]=1;});reset(true);renderYellow();var st=await rpc('getPublicState',[null]);var existing=Array.isArray(st&&st.tempPairs)?st.tempPairs.slice():[];existing=existing.filter(function(p){var all=tempIds(p);return !ids.some(function(id){return all.indexOf(String(id))>=0;});});existing.push({members:ids.map(String),pairA:ids.map(String),pairB:[],zone:loc.type,createdAt:Date.now()});var saved=await rpc('setTempPairs',[null,existing]);if(saved&&Array.isArray(saved.tempPairs))absorb(saved);else renderYellow();toast('2명 팀설정 완료',false);}catch(e){yellow=before;renderYellow();toast(String(e&&e.message||e||'팀설정 실패'),true);}}
  function emptyTarget(el){if(!el)return null;var raw=String(el.getAttribute('onclick')||'');var m=raw.match(/handleEmptySlotTap\(['\"]([^'\"]+)['\"],['\"]([^'\"]+)['\"],\s*(\d+)/);if(!m)return null;var type=String(m[1]),idx=String(m[2]);return {kind:'empty',type:type,key:type==='wait'?String(Number(idx)+1):idx,slotIndex:Number(m[3]),el:el,id:'e|'+type+'|'+idx+'|'+m[3]};}
  async function executeSwap(src,dst){try{await rpc('swapMembers',[null,src.map(String),dst.map(String)]);reset();if(typeof renderState==='function')renderState();setTimeout(renderYellow,0);toast(src.length+'명 교환 완료',false);}catch(e){toast(String(e&&e.message||e||'교환 실패'),true);}}
  async function executeMove(){var src=selected.slice(),dst=targets.slice();if(src.length!==dst.length)return;try{if(targetKind==='member'){await rpc('swapMembers',[null,src,dst.map(function(t){return String(t.id);})]);}else{for(var i=0;i<src.length;i++){var t=dst[i];await rpc('moveOrSwapMember',[null,String(src[i]),String(t.type),String(t.type==='wait'?Number(t.key)-1:t.key),'']);}}reset();if(typeof renderState==='function')renderState();setTimeout(renderYellow,0);toast(src.length+'명 이동/교환 완료',false);}catch(e){toast(String(e&&e.message||e||'이동/교환 실패'),true);phase='source';targets=[];targetKind='';renderGreen();renderPanel();}}
  function addTarget(t){if(!t)return;if(targetKind&&targetKind!==t.kind){toast('빈자리와 사람은 섞어서 선택할 수 없습니다.',true);return;}var key=t.kind==='member'?'m|'+t.id:t.id;var at=targets.findIndex(function(x){return (x.kind==='member'?'m|'+x.id:x.id)===key;});if(at>=0){targets.splice(at,1);if(!targets.length)targetKind='';renderGreen();renderPanel();return;}if(targets.length>=selected.length)return;targetKind=t.kind;targets.push(t);renderGreen();renderPanel();if(targets.length===selected.length)executeMove();}
  function beginAutoTarget(t){phase='target';targets=[];targetKind='';addTarget(t);}
  function onClick(event){if(event.button>0)return;if(event.target&&event.target.closest&&event.target.closest('#jm-admin-multi-action'))return;ensureStyle();if(phase==='target'){var ee=event.target&&event.target.closest&&event.target.closest('.quick-empty-slot,.person.empty');if(ee&&ee.closest('#adminApp')){var et=emptyTarget(ee);if(et){event.preventDefault();event.stopPropagation();if(event.stopImmediatePropagation)event.stopImmediatePropagation();addTarget(et);return;}}var tc=card(event.target);if(tc){var tid=idOf(tc);if(!tid||selected.indexOf(tid)>=0)return;event.preventDefault();event.stopPropagation();if(event.stopImmediatePropagation)event.stopImmediatePropagation();addTarget({kind:'member',id:tid});return;}return;}var sourceEmpty=event.target&&event.target.closest&&event.target.closest('.quick-empty-slot,.person.empty');if(sourceEmpty&&sourceEmpty.closest('#adminApp')&&selected.length&&selected.length!==2){var sourceEt=emptyTarget(sourceEmpty);if(sourceEt){event.preventDefault();event.stopPropagation();if(event.stopImmediatePropagation)event.stopImmediatePropagation();beginAutoTarget(sourceEt);return;}}if(event.target&&event.target.closest&&event.target.closest('button,input,textarea,select,a,[role="button"]'))return;var c=card(event.target);if(!c)return;var id=idOf(c);if(!id)return;var loc=locate(id);if(!loc)return;event.preventDefault();event.stopPropagation();if(event.stopImmediatePropagation)event.stopImmediatePropagation();if(!selected.length)clearMessageSelection();var at=selected.indexOf(id);if(at>=0){selected.splice(at,1);if(!selected.length)group=null;renderGreen();renderPanel();return;}if(!selected.length){selected=[id];group=signature(id);renderGreen();renderPanel();return;}var same=signature(id)===group;if(same){if(selected.length<4){selected.push(id);renderGreen();renderPanel();return;}toast('한 번에 최대 4명까지 선택할 수 있습니다.',true);return;}if(selected.length===1){var left=selected[0];renderGreen();executeSwap([left],[id]);return;}if(selected.length===3||selected.length===4){beginAutoTarget({kind:'member',id:id});return;}toast('2명 선택 시 이동/교환 또는 팀설정을 먼저 선택하세요.',false);}
  async function refreshTeams(){try{var s=await rpc('getPublicState',[null]);absorb(s);}catch(_){} }
  function wrapRenderState(){if(typeof window.renderState!=='function'||window.renderState.__jmYellowStableV2055)return;var original=window.renderState;var wrapped=function(){var out=original.apply(this,arguments);setTimeout(function(){renderGreen();renderYellow();},0);return out;};wrapped.__jmYellowStableV2055=true;window.renderState=wrapped;}
  function watch(){var a=app();if(!a){setTimeout(watch,120);return;}ensureStyle();wrapRenderState();refreshTeams();}
  ensureStyle();window.addEventListener('click',onClick,true);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch,{once:true});else setTimeout(watch,0);
})();
