(function installJayumintonAdminLayoutWait4CompactV2076(){
'use strict';
if(typeof IS_ADMIN!=='undefined'&&!IS_ADMIN)return;
if(window.__JAYUMINTON_ADMIN_LAYOUT_WAIT4_COMPACT_V2076__)return;
window.__JAYUMINTON_ADMIN_LAYOUT_WAIT4_COMPACT_V2076__=true;

function root(){return document.getElementById('adminApp');}
function toast(text,bad){var old=document.getElementById('jmV2076Toast');if(old)old.remove();var n=document.createElement('div');n.id='jmV2076Toast';n.textContent=String(text||'');n.style.cssText='position:fixed;left:50%;top:max(10px,env(safe-area-inset-top));transform:translateX(-50%);z-index:2147483647;padding:8px 12px;border-radius:10px;background:'+(bad?'#991b1b':'#111827')+';color:#fff;font-size:12px;font-weight:900;box-shadow:0 6px 20px rgba(0,0,0,.22)';document.body.appendChild(n);setTimeout(function(){n.remove();},1700);}
function memberId(card){if(!card)return '';for(var a of ['data-member-id','data-memberid','data-player-id','data-id','data-member']){var id=String(card.getAttribute&&card.getAttribute(a)||'');if(id)return id;}var n=card.querySelector&&card.querySelector('[data-member-id],[data-memberid],[data-player-id],[data-id],[data-member]');return n?memberId(n):'';}
function selectedIds(){var ids=[];var r=root();if(!r)return ids;r.querySelectorAll('.jm-unlimited-check').forEach(function(check){var c=check.closest('[data-member-id],[data-memberid],[data-player-id],[data-id],[data-member],.member,.person,.quick-member,.member-card,.member-item,.player-card,.court-player');var id=memberId(c);if(id&&ids.indexOf(id)<0)ids.push(id);});return ids;}
function renderResult(v){try{var x=v;for(var i=0;i<3;i++){if(x&&x.state&&typeof x.state==='object')x=x.state;else break;}if(x&&typeof window.renderState==='function')window.renderState(x);}catch(_){} }
function rpc(name,args){return typeof window.server==='function'?window.server(name,args):Promise.reject(new Error('서버 연결을 찾을 수 없습니다.'));}
function quickCard(){var q=document.getElementById('quickSelectedCount');if(q){var c=q.closest('.card');if(c)return c;}var r=root();if(!r)return null;for(var h of r.querySelectorAll('h1,h2,h3,strong'))if(String(h.textContent||'').indexOf('빠른 코트배정')>=0)return h.closest('.card')||h.parentElement;return null;}
function quickHeader(card){if(!card)return null;return card.querySelector('.quick-roster-header')||Array.from(card.children).find(function(el){return /빠른 코트배정/.test(String(el.textContent||''));})||card.firstElementChild;}
function placeToolbarClean(){var bar=document.getElementById('jmUnlimitedToolbar'),card=quickCard();if(!bar||!card)return false;var head=quickHeader(card);bar.style.setProperty('position','relative','important');bar.style.setProperty('inset','auto','important');bar.style.setProperty('transform','none','important');bar.style.setProperty('float','none','important');bar.style.setProperty('width','auto','important');bar.style.setProperty('clear','both','important');bar.style.setProperty('z-index','1','important');if(head&&head.parentNode===card&&head.nextSibling!==bar)card.insertBefore(bar,head.nextSibling);return true;}
function wait4Box(){var r=root();if(!r)return null;var all=r.querySelectorAll('section,.card,div');for(var n of all){var heads=n.querySelectorAll('h1,h2,h3,h4,strong,.title,.wait-title');for(var h of heads){if(/^대기\s*4\b/.test(String(h.textContent||'').trim()))return n;}}return null;}
function wait4Second(){var box=wait4Box();if(!box)return null;var candidates=Array.from(box.querySelectorAll('.empty,.quick-empty-slot,[class*="empty"],[onclick]')).filter(function(el){var t=String(el.textContent||'').replace(/\s+/g,'');return t.indexOf('비어있음')>=0||el.classList.contains('empty')||el.classList.contains('quick-empty-slot');});return candidates[1]||null;}
function enableWait4Second(){var slot=wait4Second();if(!slot)return false;slot.disabled=false;slot.removeAttribute('disabled');slot.removeAttribute('aria-disabled');slot.removeAttribute('inert');slot.classList.remove('disabled','is-disabled','inactive','non-clickable');slot.style.setProperty('pointer-events','auto','important');slot.style.setProperty('opacity','1','important');slot.style.setProperty('cursor','pointer','important');slot.style.setProperty('filter','none','important');slot.setAttribute('data-jm-v2076-wait4-second','1');return true;}
function installWait4Direct(){var r=root();if(!r||r.__jmV2076Wait4Direct)return;r.__jmV2076Wait4Direct=true;r.addEventListener('click',function(e){var slot=e.target&&e.target.closest&&e.target.closest('[data-jm-v2076-wait4-second="1"]');if(!slot)return;var ids=selectedIds();if(!ids.length)return; e.preventDefault();e.stopImmediatePropagation();rpc('assignMembersToWaitGroup',[null,3,ids]).then(function(v){renderResult(v);toast(ids.length+'명 대기4에 배정');}).catch(function(err){toast(String(err&&err.message||err||'대기4 배정 실패'),true);});},true);}
function compactBottom(){var r=root();if(!r)return false;var move=document.getElementById('jmBottomMoveButton');var buttons=Array.from(r.querySelectorAll('button'));function find(t){return buttons.find(function(b){return String(b.textContent||'').trim()===t;})||null;}var undo=find('실행취소'),refresh=find('새로고침'),auto=find('자동배정');if(!move||!undo||!refresh||!auto)return false;var p=refresh.parentElement;if(!p||undo.parentElement!==p||auto.parentElement!==p||move.parentElement!==p)return false;p.classList.add('jm-v2076-bottom-row');[undo,move,refresh,auto].forEach(function(b){b.classList.add('jm-v2076-bottom-btn');});return true;}
function fixNewBadge(){var r=root();if(!r)return;var nodes=Array.from(r.querySelectorAll('.new,.new-badge,.badge-new,.member-new,.jm-new,.new-label,[data-new-badge]'));nodes.forEach(function(n){if(String(n.textContent||'').trim()==='신규'||/new/i.test(n.className||'')){n.classList.add('jm-v2076-new-badge');var card=n.closest('.member,.person,.quick-member,.member-card,.member-item,.player-card,.court-player,[data-member-id],[data-memberid],[data-player-id]');if(card)card.classList.add('jm-v2076-has-new');}});}
function installStyle(){if(document.getElementById('jmV2076Style'))return;var s=document.createElement('style');s.id='jmV2076Style';s.textContent=''
+'#jmUnlimitedToolbar{position:relative!important;inset:auto!important;transform:none!important;float:none!important;clear:both!important;width:auto!important;max-width:100%!important;margin:8px 0 10px!important;z-index:1!important;box-sizing:border-box!important}'
+'#jmUnlimitedToolbar *{box-sizing:border-box!important}'
+'#adminApp .jm-v2076-bottom-row{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:4px!important;align-items:stretch!important}'
+'#adminApp .jm-v2076-bottom-btn{min-width:0!important;min-height:31px!important;height:31px!important;padding:2px 3px!important;margin:0!important;font-size:10px!important;line-height:1!important;font-weight:900!important;white-space:nowrap!important;border-radius:7px!important;letter-spacing:-.35px!important}'
+'#adminApp [data-jm-v2076-wait4-second="1"]{pointer-events:auto!important;opacity:1!important;cursor:pointer!important;filter:none!important}'
+'#adminApp .jm-v2076-new-badge{position:relative!important;top:auto!important;left:auto!important;right:auto!important;bottom:auto!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;margin:0 0 4px 0!important;padding:1px 5px!important;min-height:15px!important;line-height:1.15!important;font-size:9px!important;font-weight:900!important;z-index:2!important;vertical-align:middle!important}'
+'#adminApp .jm-v2076-has-new{padding-top:4px!important}'
+'@media(max-width:430px){#adminApp .jm-v2076-bottom-btn{font-size:9px!important;letter-spacing:-.5px!important;padding:2px 1px!important}}';(document.head||document.documentElement).appendChild(s);}
function maintain(){placeToolbarClean();enableWait4Second();compactBottom();fixNewBadge();}
function boot(){installStyle();installWait4Direct();var i=0;(function retry(){maintain();if(++i<120)setTimeout(retry,100);})();var r=root();if(r&&!r.__jmV2076Observer){var q=false;r.__jmV2076Observer=new MutationObserver(function(){if(q)return;q=true;requestAnimationFrame(function(){q=false;maintain();});});r.__jmV2076Observer.observe(r,{childList:true,subtree:true,attributes:true,attributeFilter:['class','style','disabled','aria-disabled']});}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else setTimeout(boot,0);
})();
