function memberAnywhereLocation_(memberId){
  memberId=String(memberId||'');var courts=readCourts_();var courtKeys=Object.keys(courts);
  for(var c=0;c<courtKeys.length;c+=1){var courtNo=courtKeys[c];var court=(courts[courtNo]||[]);var courtPos=court.indexOf(memberId);if(courtPos>=0)return {type:'court',courtNo:String(courtNo),position:courtPos};}
  var waitGroups=readWaitGroups_();for(var g=0;g<waitGroups.length;g+=1){var waitPos=(waitGroups[g]||[]).indexOf(memberId);if(waitPos>=0)return {type:'wait',group:g,position:waitPos};}
  var member=readMembers_().find(function(item){return item&&String(item.id)===memberId;});return member?{type:'status',status:String(member.status||'active')}:null;
}
function memberAnywhereLocationKey_(location){if(!location)return '';if(location.type==='court')return 'court:'+location.courtNo+':'+location.position;if(location.type==='wait')return 'wait:'+location.group+':'+location.position;if(location.type==='status')return 'status:'+location.status;return '';}
function memberAnywhereSnapshot_(memberId){var location=memberAnywhereLocation_(memberId);return {memberId:String(memberId||''),locationKey:memberAnywhereLocationKey_(location)};}
function memberAnywhereSwapSnapshot_(fromMemberId,toMemberId){return {from:memberAnywhereSnapshot_(fromMemberId),to:memberAnywhereSnapshot_(toMemberId)};}
function memberAnywhereSwapCacheKey_(memberId){return 'ANYWHERE_SWAP_'+String(memberId||'');}
function memberAnywhereOutgoingCacheKey_(memberId){return 'ANYWHERE_SWAP_OUT_'+String(memberId||'');}
function memberAnywhereSwapRequest_(requesterId,targetId){return {requesterId:String(requesterId||''),targetId:String(targetId||''),snapshot:memberAnywhereSwapSnapshot_(requesterId,targetId),createdAt:Date.now()};}
function memberAnywherePutSwapRequest_(targetId,request){var cache=CacheService.getDocumentCache();cache.put(memberAnywhereSwapCacheKey_(targetId),JSON.stringify(request),300);cache.put(memberAnywhereOutgoingCacheKey_(request.requesterId),String(targetId),300);}
function memberAnywhereReadSwapRaw_(memberId){return CacheService.getDocumentCache().get(memberAnywhereSwapCacheKey_(memberId));}
function memberAnywhereReadOutgoingTarget_(memberId){return CacheService.getDocumentCache().get(memberAnywhereOutgoingCacheKey_(memberId));}
function memberAnywhereReadSwapRequest_(memberId){var raw=memberAnywhereReadSwapRaw_(memberId);if(!raw)return null;try{return JSON.parse(raw);}catch(error){CacheService.getDocumentCache().remove(memberAnywhereSwapCacheKey_(memberId));return null;}}
function memberAnywhereSnapshotStillValid_(snapshot){if(!snapshot||!snapshot.from||!snapshot.to)return false;return memberAnywhereSnapshot_(snapshot.from.memberId).locationKey===snapshot.from.locationKey&&memberAnywhereSnapshot_(snapshot.to.memberId).locationKey===snapshot.to.locationKey;}
function memberAnywhereRequestStillValid_(request){return !!(request&&request.requesterId&&request.targetId&&memberAnywhereSnapshotStillValid_(request.snapshot));}
function memberAnywhereSameRequest_(first,second){return !!(first&&second&&String(first.requesterId||'')===String(second.requesterId||'')&&String(first.targetId||'')===String(second.targetId||'')&&Number(first.createdAt||0)===Number(second.createdAt||0));}
function memberAnywhereExpectedRequestMatches_(request,expectedRequesterId,expectedCreatedAt){if(expectedRequesterId==null&&expectedCreatedAt==null)return true;return !!(request&&String(request.requesterId||'')===String(expectedRequesterId||'')&&Number(request.createdAt||0)===Number(expectedCreatedAt||0));}
function memberAnywhereReadActiveOutgoingTarget_(memberId){memberId=String(memberId||'');var targetId=memberAnywhereReadOutgoingTarget_(memberId);if(!targetId)return '';var request=memberAnywhereReadSwapRequest_(targetId);if(!request||String(request.requesterId)!==memberId||String(request.targetId)!==String(targetId)){var outgoingTarget=memberAnywhereReadOutgoingTarget_(memberId);if(String(outgoingTarget||'')===String(targetId))CacheService.getDocumentCache().remove(memberAnywhereOutgoingCacheKey_(memberId));return '';}if(!memberAnywhereRequestStillValid_(request)){memberAnywhereClearSwapRequest_(targetId,request);return '';}return String(targetId);}
function memberAnywhereClearSwapRequest_(memberId,expectedRequest){var cache=CacheService.getDocumentCache();var request=memberAnywhereReadSwapRequest_(memberId);if(expectedRequest&&!memberAnywhereSameRequest_(request,expectedRequest))return false;cache.remove(memberAnywhereSwapCacheKey_(memberId));if(request&&request.requesterId){var outgoingTarget=memberAnywhereReadOutgoingTarget_(request.requesterId);if(String(outgoingTarget||'')===String(memberId||''))cache.remove(memberAnywhereOutgoingCacheKey_(request.requesterId));}return true;}
function memberGetAnywhereSwapRequest(sessionToken,memberId){memberId=memberSessionAuth_(sessionToken,memberId);var request=memberAnywhereReadSwapRequest_(memberId);if(!request||String(request.targetId)!==memberId)return null;if(!memberAnywhereRequestStillValid_(request)){memberAnywhereClearSwapRequest_(memberId,request);return null;}return request;}
function memberGetAnywhereOutgoingSwap(sessionToken,memberId){memberId=memberSessionAuth_(sessionToken,memberId);var targetId=memberAnywhereReadActiveOutgoingTarget_(memberId);if(!targetId)return null;var request=memberAnywhereReadSwapRequest_(targetId);if(!request||String(request.requesterId)!==memberId||String(request.targetId)!==String(targetId)){var outgoingTarget=memberAnywhereReadOutgoingTarget_(memberId);if(String(outgoingTarget||'')===String(targetId))CacheService.getDocumentCache().remove(memberAnywhereOutgoingCacheKey_(memberId));return null;}var snapshot=request.snapshot||{};var from=snapshot.from||{};var to=snapshot.to||{};return {targetId:String(targetId),createdAt:Number(request.createdAt||0),requesterLocationKey:String(from.locationKey||''),targetLocationKey:String(to.locationKey||'')};}
function memberCancelAnywhereSwap(sessionToken,memberId,expectedTargetId,expectedCreatedAt){memberId=memberSessionAuth_(sessionToken,memberId);var lock=LockService.getDocumentLock();if(!lock.tryLock(3000))return {ok:false,message:'다른 자리 요청을 처리 중이에요. 잠시 후 다시 시도해 주세요.'};try{var targetId=memberAnywhereReadActiveOutgoingTarget_(memberId);if(!targetId)return {ok:false,message:'취소할 자리교환 요청이 없거나 이미 처리됐어요.'};var request=memberAnywhereReadSwapRequest_(targetId);if(!request||String(request.requesterId)!==memberId||String(request.targetId)!==String(targetId))return {ok:false,message:'취소할 자리교환 요청이 없거나 이미 처리됐어요.'};if((expectedTargetId!=null||expectedCreatedAt!=null)&&(String(targetId)!==String(expectedTargetId||'')||Number(request.createdAt||0)!==Number(expectedCreatedAt||0)))return {ok:false,message:'자리교환 요청이 변경됐어요. 현재 요청을 다시 확인해 주세요.'};if(!memberAnywhereClearSwapRequest_(targetId,request))return {ok:false,message:'자리교환 요청 상태가 변경됐어요. 현황을 새로고침해 주세요.'};return {ok:true,message:'보낸 자리교환 요청을 취소했어요.'};}finally{lock.releaseLock();}}
function memberRejectAnywhereSwap(sessionToken,memberId,expectedRequesterId,expectedCreatedAt){memberId=memberSessionAuth_(sessionToken,memberId);var lock=LockService.getDocumentLock();if(!lock.tryLock(3000))return {ok:false,message:'다른 자리 요청을 처리 중이에요. 잠시 후 다시 시도해 주세요.'};try{var request=memberAnywhereReadSwapRequest_(memberId);if(!request||String(request.targetId)!==memberId)return {ok:false,message:'교환 요청이 없거나 만료됐어요.'};if(!memberAnywhereExpectedRequestMatches_(request,expectedRequesterId,expectedCreatedAt))return {ok:false,message:'자리교환 요청이 변경됐어요. 새 요청을 확인해 주세요.'};if(!memberAnywhereClearSwapRequest_(memberId,request))return {ok:false,message:'자리교환 요청이 변경되었거나 이미 만료됐어요. 새 요청을 확인해 주세요.'};return {ok:true,message:'자리 교환 요청을 거절했어요.'};}finally{lock.releaseLock();}}
function memberAnywhereStatusForLocation_(location){if(location.type==='court')return 'playing';if(location.type==='wait')return 'waiting';return String(location.status||'active');}
function memberAnywhereApplyStatus_(member,location){member.status=memberAnywhereStatusForLocation_(location);}
function memberAnywhereMemberById_(members,memberId){return members.find(function(member){return String(member.id)===String(memberId);})||null;}
function memberAnywhereRemovePair_(firstId,secondId,courts,waitGroups){var ids={};ids[String(firstId)]=true;ids[String(secondId)]=true;Object.keys(courts).forEach(function(no){courts[no]=(courts[no]||[]).filter(function(id){return !ids[String(id)];});});for(var g=0;g<waitGroups.length;g+=1)waitGroups[g]=(waitGroups[g]||[]).filter(function(id){return !ids[String(id)];});}
function memberAnywhereInsertAt_(list,position,memberId){position=Math.max(0,Math.min(Number(position)||0,list.length));list.splice(position,0,String(memberId));}
function memberAnywherePlaceAtLocation_(location,memberId,courts,waitGroups){if(!location)return;if(location.type==='court'){var no=String(location.courtNo);if(!courts[no])courts[no]=[];memberAnywhereInsertAt_(courts[no],location.position,memberId);return;}if(location.type==='wait'){var group=Number(location.group);while(waitGroups.length<=group)waitGroups.push([]);memberAnywhereInsertAt_(waitGroups[group],location.position,memberId);}}
function memberAnywhereSameList_(firstLocation,secondLocation){if(!firstLocation||!secondLocation||firstLocation.type!==secondLocation.type)return false;if(firstLocation.type==='court')return String(firstLocation.courtNo)===String(secondLocation.courtNo);if(firstLocation.type==='wait')return Number(firstLocation.group)===Number(secondLocation.group);return false;}
function memberAnywhereSwapSameList_(firstId,secondId,firstLocation,secondLocation,courts,waitGroups){var list=null;if(firstLocation.type==='court')list=courts[String(firstLocation.courtNo)]||null;else if(firstLocation.type==='wait')list=waitGroups[Number(firstLocation.group)]||null;if(!list)return false;var firstPosition=Number(firstLocation.position),secondPosition=Number(secondLocation.position);if(!isFinite(firstPosition)||!isFinite(secondPosition)||firstPosition<0||secondPosition<0||firstPosition>=list.length||secondPosition>=list.length)return false;if(String(list[firstPosition])!==String(firstId)||String(list[secondPosition])!==String(secondId))return false;list[firstPosition]=String(secondId);list[secondPosition]=String(firstId);return true;}
function memberAnywhereSwapAll_(firstId,secondId,firstLocation,secondLocation){var courts=readCourts_();var waitGroups=readWaitGroups_();var members=readMembers_();var first=memberAnywhereMemberById_(members,firstId),second=memberAnywhereMemberById_(members,secondId);if(!first||!second)return false;if(memberAnywhereSameList_(firstLocation,secondLocation)){if(!memberAnywhereSwapSameList_(firstId,secondId,firstLocation,secondLocation,courts,waitGroups))return false;}else{memberAnywhereRemovePair_(firstId,secondId,courts,waitGroups);memberAnywherePlaceAtLocation_(secondLocation,firstId,courts,waitGroups);memberAnywherePlaceAtLocation_(firstLocation,secondId,courts,waitGroups);}memberAnywhereApplyStatus_(first,secondLocation);memberAnywhereApplyStatus_(second,firstLocation);writeMembers_(members);writeCourts_(courts,readCourtStartedAt_());writeWaitGroups_(waitGroups);touch_();return memberAnywhereLocationKey_(memberAnywhereLocation_(firstId))===memberAnywhereLocationKey_(secondLocation)&&memberAnywhereLocationKey_(memberAnywhereLocation_(secondId))===memberAnywhereLocationKey_(firstLocation);}
function memberAcceptAnywhereSwap(sessionToken,memberId,expectedRequesterId,expectedCreatedAt){memberId=memberSessionAuth_(sessionToken,memberId);var lock=LockService.getDocumentLock();if(!lock.tryLock(5000))return {ok:false,message:'다른 자리 변경을 처리 중이에요. 잠시 후 다시 시도해 주세요.'};try{var request=memberAnywhereReadSwapRequest_(memberId);if(!request||String(request.targetId)!==memberId)return {ok:false,message:'교환 요청이 없거나 만료됐어요.'};if(!memberAnywhereExpectedRequestMatches_(request,expectedRequesterId,expectedCreatedAt))return {ok:false,message:'자리교환 요청이 변경됐어요. 새 요청을 확인해 주세요.'};var snapshot=request.snapshot||{};if(snapshot.from&&snapshot.to&&snapshot.from.locationKey&&snapshot.from.locationKey===snapshot.to.locationKey){memberAnywhereClearSwapRequest_(memberId,request);return {ok:false,message:'이미 같은 상태라 자리교환이 필요하지 않아요.'};}if(!memberAnywhereSnapshotStillValid_(request.snapshot)){memberAnywhereClearSwapRequest_(memberId,request);return {ok:false,message:'자리 상태가 변경되어 교환할 수 없어요.'};}var firstLocation=memberAnywhereLocation_(request.requesterId);var secondLocation=memberAnywhereLocation_(memberId);var ok=memberAnywhereSwapAll_(request.requesterId,memberId,firstLocation,secondLocation);memberAnywhereClearSwapRequest_(memberId,request);return ok?{ok:true,message:'두 사람의 자리를 서로 교환했어요.',state:getPublicState()}:{ok:false,message:'두 사람의 위치를 정확히 교환하지 못했어요. 현황을 새로고침해 주세요.',state:getPublicState()};}finally{lock.releaseLock();}}
function memberRequestAnywhereSwap(sessionToken,memberId,targetId){memberId=memberSessionAuth_(sessionToken,memberId);targetId=String(targetId||'');if(!targetId||targetId===memberId)return {ok:false,message:'교환할 회원을 확인해 주세요.'};var members=readMembers_();if(!memberAnywhereMemberById_(members,targetId))return {ok:false,message:'교환할 회원을 찾을 수 없어요.'};var lock=LockService.getDocumentLock();if(!lock.tryLock(3000))return {ok:false,message:'다른 자리 요청을 처리 중이에요. 잠시 후 다시 시도해 주세요.'};try{var outgoingTarget=memberAnywhereReadActiveOutgoingTarget_(memberId);if(outgoingTarget)return {ok:false,message:outgoingTarget===targetId?'이미 이 회원에게 자리교환을 요청했어요.':'먼저 보낸 자리교환 요청을 처리해 주세요.'};var incoming=memberAnywhereReadSwapRequest_(memberId);if(incoming&&!memberAnywhereRequestStillValid_(incoming)){memberAnywhereClearSwapRequest_(memberId,incoming);incoming=null;}if(incoming)return {ok:false,message:'먼저 받은 자리교환 요청을 처리해 주세요.'};var targetOutgoing=memberAnywhereReadActiveOutgoingTarget_(targetId);if(targetOutgoing)return {ok:false,message:'상대방이 다른 자리교환 요청을 처리 중이에요.'};var pending=memberAnywhereReadSwapRequest_(targetId);if(pending&&!memberAnywhereRequestStillValid_(pending)){memberAnywhereClearSwapRequest_(targetId,pending);pending=null;}if(pending){if(String(pending.requesterId)===memberId)return {ok:false,message:'이미 이 회원에게 자리교환을 요청했어요.'};return {ok:false,message:'상대방이 다른 자리교환 요청을 처리 중이에요.'};}var request=memberAnywhereSwapRequest_(memberId,targetId);if(!request.snapshot.from.locationKey||!request.snapshot.to.locationKey)return {ok:false,message:'현재 자리를 확인할 수 없어요.'};if(request.snapshot.from.locationKey===request.snapshot.to.locationKey)return {ok:false,message:'이미 같은 상태라 자리교환이 필요하지 않아요.'};memberAnywherePutSwapRequest_(targetId,request);return {ok:true,message:'자리 교환을 요청했어요.',createdAt:Number(request.createdAt||0),requesterLocationKey:String(request.snapshot.from.locationKey||''),targetLocationKey:String(request.snapshot.to.locationKey||'')};}finally{lock.releaseLock();}}

function memberMoveSelf(sessionToken,memberId,destination){
  memberId=memberSessionAuth_(sessionToken,memberId);destination=destination||{};
  var lock=LockService.getDocumentLock();if(!lock.tryLock(5000))return {ok:false,message:'다른 자리 변경을 처리 중이에요. 잠시 후 다시 시도해 주세요.'};
  try{
    if(memberAnywhereReadActiveOutgoingTarget_(memberId))return {ok:false,message:'보낸 자리교환 요청을 먼저 처리해 주세요.'};
    var incoming=memberAnywhereReadSwapRequest_(memberId);if(incoming&&!memberAnywhereRequestStillValid_(incoming)){memberAnywhereClearSwapRequest_(memberId,incoming);incoming=null;}if(incoming)return {ok:false,message:'받은 자리교환 요청을 먼저 처리해 주세요.'};
    var courts=readCourts_(),waitGroups=readWaitGroups_(),members=readMembers_(),startedAt=readCourtStartedAt_(),member=memberAnywhereMemberById_(members,memberId);if(!member)return {ok:false,message:'회원 정보를 확인할 수 없어요.'};
    var type=String(destination.type||''),status=String(destination.status||'');
    if(type==='wait-auto'){
      var autoGroup=-1;for(var autoIndex=0;autoIndex<waitGroups.length;autoIndex+=1){if((waitGroups[autoIndex]||[]).length<GROUP_SIZE){autoGroup=autoIndex;break;}}
      if(autoGroup<0)return {ok:false,message:'현재 대기목록에 빈자리가 없어요.'};
      type='wait';destination={type:'wait',group:autoGroup};
    }
    if(type==='court'){
      var courtNo=String(destination.courtNo||''),court=courts[courtNo];if(!court)return {ok:false,message:'코트를 확인할 수 없어요.'};if(court.length>=GROUP_SIZE)return {ok:false,message:'선택한 코트에 빈자리가 없어요.'};
    }else if(type==='wait'){
      var group=Number(destination.group);if(!isFinite(group)||group<0||group>=waitGroups.length)return {ok:false,message:'대기 자리를 확인할 수 없어요.'};if((waitGroups[group]||[]).length>=GROUP_SIZE)return {ok:false,message:'선택한 대기조에 빈자리가 없어요.'};
    }else if(type==='status'){
      if(['active','rest','away','before'].indexOf(status)<0)return {ok:false,message:'이동 상태를 확인할 수 없어요.'};
    }else return {ok:false,message:'이동할 위치를 확인해 주세요.'};
    Object.keys(courts).forEach(function(no){var before=(courts[no]||[]).length;courts[no]=(courts[no]||[]).filter(function(id){return String(id)!==memberId;});if(courts[no].length!==before&&courts[no].length<GROUP_SIZE)startedAt[no]='';});
    for(var g=0;g<waitGroups.length;g+=1)waitGroups[g]=(waitGroups[g]||[]).filter(function(id){return String(id)!==memberId;});
    if(type==='court'){var targetCourtNo=String(destination.courtNo);courts[targetCourtNo].push(memberId);startedAt[targetCourtNo]=courts[targetCourtNo].length===GROUP_SIZE?(startedAt[targetCourtNo]||new Date().toISOString()):'';member.status='playing';}
    else if(type==='wait'){waitGroups[Number(destination.group)].push(memberId);member.status='waiting';}
    else member.status=status;
    writeMembers_(members);writeCourts_(courts,startedAt);writeWaitGroups_(waitGroups);touch_();
    return {ok:true,message:type==='court'?'코트에 배정했어요.':type==='wait'?'코트 배정되었어요.':status==='rest'?'휴식으로 이동했어요.':status==='away'?'귀가로 이동했어요.':status==='before'?'도착전으로 이동했어요.':'코트배정대기에 등록했어요.',state:getPublicState()};
  }finally{lock.releaseLock();}
}

function memberReturnSelfToWait(sessionToken,memberId){
  return memberMoveSelf(sessionToken,memberId,{type:'wait-auto'});
}