#!/usr/bin/env python3
from pathlib import Path
import sys


path = Path(sys.argv[1])
s = path.read_text(encoding="utf-8")

# Diagnostic-only layer on top of the verified v1.2.3 overlay candidate.
# Do not change the visible alert behavior here; only expose the real native
# execution path in privacy-safe form.
for old, new in (
    ("v1.2.3-confirmed-overlay.apk", "v1.2.4-diagnostic.apk"),
    ("user-native-push-v1.2.3.txt", "user-native-push-v1.2.4-diagnostic.txt"),
    ('VERSION="1.2.3"', 'VERSION="1.2.4"'),
    ('VERSION_CODE="123"', 'VERSION_CODE="124"'),
    ("versionCode 123", "versionCode 124"),
    ("versionCode='123'", "versionCode='124'"),
    ("versionName '1.2.3'", "versionName '1.2.4'"),
    ("versionName='1.2.3'", "versionName='1.2.4'"),
    ('USER_APP_VERSION = "1.2.3"', 'USER_APP_VERSION = "1.2.4"'),
    ("JayumintonUserNative/1.2.3", "JayumintonUserNative/1.2.4"),
    ("JayumintonNativeAndroid/1.2.3", "JayumintonNativeAndroid/1.2.4"),
    ('APP_VERSION = "1.2.3"', 'APP_VERSION = "1.2.4"'),
    ("version=1.2.3", "version=1.2.4"),
    ("version_code=123", "version_code=124"),
    ("jayuminton_wait1_native_v123", "jayuminton_wait1_native_v124_diag"),
    ("jayuminton_court_native_v123", "jayuminton_court_native_v124_diag"),
):
    s = s.replace(old, new)

# Replace the coarse reporter generated by the v1.2.0 diagnostic layer. Raw
# member IDs, names, tokens and assignment IDs are never posted; fingerprints
# are generated in-process and only those fingerprints leave the phone.
reporter_start = s.find('cat > "$REPORTER_JAVA" <<JAVA\n')
if reporter_start < 0:
    raise SystemExit("v124 reporter source start missing")
reporter_end = s.find('\nJAVA\n\n', reporter_start)
if reporter_end < 0:
    raise SystemExit("v124 reporter source end missing")
reporter_end += len('\nJAVA\n\n')
reporter_java = r'''cat > "$REPORTER_JAVA" <<JAVA
package com.jayuminton.admin;

import android.net.Uri;

import org.json.JSONObject;

import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public final class NativeDeliveryReporter {
    private static final String RELAY_URL = "${PUSH_URL}";
    private static final String APP_VERSION = "1.2.4";
    private static final ExecutorService EXECUTOR = Executors.newSingleThreadExecutor();

    private NativeDeliveryReporter() {}

    private static String hashValue(String value) {
        String input = value == null ? "" : value.trim();
        if (input.isEmpty()) return "";
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] bytes = digest.digest(input.getBytes(StandardCharsets.UTF_8));
            StringBuilder out = new StringBuilder();
            for (int i = 0; i < 10 && i < bytes.length; i++) {
                out.append(String.format(Locale.US, "%02x", bytes[i] & 0xff));
            }
            return out.toString();
        } catch (Exception ignored) {
            return "";
        }
    }

    // Backward-compatible entry point for earlier generated call sites.
    public static void report(String stage, String eventType, boolean hasTargetMemberId,
                              boolean selectedMemberMatches, boolean notificationPosted,
                              boolean fullScreenAllowed, boolean vibrationCancelled) {
        reportPath(stage, eventType, "", "", "", selectedMemberMatches,
                notificationPosted, fullScreenAllowed, false,
                !vibrationCancelled, vibrationCancelled, "native_legacy", "");
    }

    public static void reportPath(String stage, String eventType, String courtNo,
                                  String targetMemberId, String selectedMemberId,
                                  boolean selectedMemberMatches, boolean notificationPosted,
                                  boolean fullScreenAllowed, boolean fullScreenAttempted,
                                  boolean vibrationActive, boolean vibrationCancelled,
                                  String source, String traceId) {
        EXECUTOR.execute(() -> {
            HttpURLConnection connection = null;
            try {
                JSONObject payload = new JSONObject();
                payload.put("action", "native_delivery_ack");
                payload.put("stage", stage == null ? "" : stage);
                payload.put("appVersion", APP_VERSION);
                payload.put("eventType", eventType == null ? "" : eventType);
                payload.put("courtNo", courtNo == null ? "" : courtNo);
                payload.put("targetMemberHash", hashValue(targetMemberId));
                payload.put("selectedMemberHash", hashValue(selectedMemberId));
                payload.put("selectedMemberMatches", selectedMemberMatches);
                payload.put("notificationPosted", notificationPosted);
                payload.put("fullScreenAllowed", fullScreenAllowed);
                payload.put("fullScreenAttempted", fullScreenAttempted);
                payload.put("vibrationActive", vibrationActive);
                payload.put("vibrationCancelled", vibrationCancelled);
                payload.put("source", source == null ? "" : source);
                payload.put("traceHash", hashValue(traceId));
                byte[] bytes = ("payload=" + Uri.encode(payload.toString()))
                        .getBytes(StandardCharsets.UTF_8);
                connection = (HttpURLConnection) new URL(RELAY_URL).openConnection();
                connection.setConnectTimeout(10000);
                connection.setReadTimeout(10000);
                connection.setRequestMethod("POST");
                connection.setInstanceFollowRedirects(false);
                connection.setDoOutput(true);
                connection.setRequestProperty(
                        "Content-Type", "application/x-www-form-urlencoded;charset=UTF-8");
                connection.setFixedLengthStreamingMode(bytes.length);
                try (OutputStream output = connection.getOutputStream()) { output.write(bytes); }
                int code = connection.getResponseCode();
                try {
                    if (code >= 200 && code < 400 && connection.getInputStream() != null) {
                        connection.getInputStream().close();
                    } else if (connection.getErrorStream() != null) {
                        connection.getErrorStream().close();
                    }
                } catch (Exception ignored) {}
            } catch (Exception ignored) {
            } finally {
                if (connection != null) connection.disconnect();
            }
        });
    }
}
JAVA

'''
s = s[:reporter_start] + reporter_java + s[reporter_end:]

# Expose only the locally selected ID to native code so it can compare before
# accepting an FCM event. The reporter hashes it before transmission.
member_anchor = '''    public static boolean isCurrentMember(Context context, String memberId) {
        String current = prefs(context.getApplicationContext()).getString(KEY_MEMBER_ID, "");
        return !current.isEmpty() && current.equals(String.valueOf(memberId == null ? "" : memberId).trim());
    }
'''
if s.count(member_anchor) != 1:
    raise SystemExit("v124 current member helper anchor missing")
s = s.replace(member_anchor, member_anchor + '''
    public static String currentMemberId(Context context) {
        return prefs(context.getApplicationContext()).getString(KEY_MEMBER_ID, "");
    }
''', 1)

# Name/member change -> immediately show that the native registrar moved to the
# new target. This is the first half of the user's name-change requirement.
member_save = '''        p.edit().putString(KEY_MEMBER_ID, newId).putString(KEY_MEMBER_NAME, newName).apply();
        if (pushEnabled(app)) {'''
if s.count(member_save) != 1:
    raise SystemExit("v124 member change anchor missing")
s = s.replace(member_save, '''        p.edit().putString(KEY_MEMBER_ID, newId).putString(KEY_MEMBER_NAME, newName).apply();
        NativeDeliveryReporter.reportPath("member_changed", "", "", newId, newId,
                !newId.isEmpty(), false, false, false, false, false,
                "native_member_selection", "");
        if (pushEnabled(app)) {''', 1)

# Show both the registration request and its HTTP outcome without logging the
# token itself.
register_anchor = '''        if (id.isEmpty() || token.isEmpty()) return;
        submitAsync("register_web_token", id, name, token);'''
if s.count(register_anchor) != 1:
    raise SystemExit("v124 native registration anchor missing")
s = s.replace(register_anchor, '''        if (id.isEmpty() || token.isEmpty()) return;
        NativeDeliveryReporter.reportPath("token_register_requested", "", "", id, id,
                true, false, false, false, false, false,
                "native_registrar", "");
        submitAsync("register_web_token", id, name, token);''', 1)

http_anchor = '''            int code = connection.getResponseCode();
            if (code >= 200 && code < 400) {
                try { if (connection.getInputStream() != null) connection.getInputStream().close(); } catch (Exception ignored) {}
            } else {
                try { if (connection.getErrorStream() != null) connection.getErrorStream().close(); } catch (Exception ignored) {}
            }
        } catch (Exception ignored) {
        } finally {'''
if s.count(http_anchor) != 1:
    raise SystemExit("v124 registration HTTP anchor missing")
s = s.replace(http_anchor, '''            int code = connection.getResponseCode();
            if (code >= 200 && code < 400) {
                try { if (connection.getInputStream() != null) connection.getInputStream().close(); } catch (Exception ignored) {}
                if ("register_web_token".equals(action)) {
                    NativeDeliveryReporter.reportPath("token_register_http_ok", "", "",
                            memberId, memberId, true, false, false, false,
                            false, false, "native_registrar_http", "");
                }
            } else {
                try { if (connection.getErrorStream() != null) connection.getErrorStream().close(); } catch (Exception ignored) {}
                if ("register_web_token".equals(action)) {
                    NativeDeliveryReporter.reportPath("token_register_http_failed", "", "",
                            memberId, memberId, true, false, false, false,
                            false, false, "native_registrar_http", "");
                }
            }
        } catch (Exception ignored) {
            if ("register_web_token".equals(action)) {
                NativeDeliveryReporter.reportPath("token_register_http_failed", "", "",
                        memberId, memberId, true, false, false, false,
                        false, false, "native_registrar_exception", "");
            }
        } finally {''', 1)

# FCM receive -> target/current comparison -> accept or reject. type and courtNo
# are non-PII; member IDs and assignmentId are fingerprinted by the reporter.
receive_old = '''        String targetMemberId = value(data, "memberId", "");
        boolean hasTargetMemberId = !targetMemberId.isEmpty();
        boolean selectedMemberMatches = !hasTargetMemberId || NativePushRegistrar.isCurrentMember(this, targetMemberId);
        NativeDeliveryReporter.report("fcm_received", type, hasTargetMemberId,
                selectedMemberMatches, false, false, false);
        if (!selectedMemberMatches) {
            NativeDeliveryReporter.report("member_rejected", type, true, false, false, false, false);
            return;
        }
        NativeDeliveryReporter.report("member_accepted", type, hasTargetMemberId,
                true, false, false, false);
        String courtNo = value(data, "courtNo", "");'''
if s.count(receive_old) != 1:
    raise SystemExit("v124 FCM receive anchor missing")
s = s.replace(receive_old, '''        String targetMemberId = value(data, "memberId", "");
        String selectedMemberId = NativePushRegistrar.currentMemberId(this);
        String courtNo = value(data, "courtNo", "");
        boolean hasTargetMemberId = !targetMemberId.isEmpty();
        boolean selectedMemberMatches = !hasTargetMemberId ||
                (!selectedMemberId.isEmpty() && selectedMemberId.equals(targetMemberId));
        NativeDeliveryReporter.reportPath("fcm_received", type, courtNo,
                targetMemberId, selectedMemberId, selectedMemberMatches,
                false, false, false, false, false,
                "native_fcm_service", assignmentIdSafe(data));
        if (!selectedMemberMatches) {
            NativeDeliveryReporter.reportPath("member_rejected", type, courtNo,
                    targetMemberId, selectedMemberId, false,
                    false, false, false, false, false,
                    "native_fcm_service", assignmentIdSafe(data));
            return;
        }
        NativeDeliveryReporter.reportPath("member_accepted", type, courtNo,
                targetMemberId, selectedMemberId, true,
                false, false, false, false, false,
                "native_fcm_service", assignmentIdSafe(data));''', 1)

value_anchor = '''    private static String value(Map<String, String> data, String key, String fallback) {
        if (data == null) return fallback;
        String value = data.get(key);
        return value == null || value.trim().isEmpty() ? fallback : value;
    }
'''
if s.count(value_anchor) != 1:
    raise SystemExit("v124 value helper anchor missing")
s = s.replace(value_anchor, value_anchor + '''
    private static String assignmentIdSafe(Map<String, String> data) {
        if (data == null) return "";
        String value = data.get("assignmentId");
        return value == null ? "" : value;
    }
''', 1)

# Center Activity fallback instrumentation. This route is particularly useful
# when Android declines an overlay/full-screen launch.
activity_start = s.find('cat > "$ALERT_JAVA" <<\'JAVA\'\n')
activity_end = s.find('\nJAVA\n\n', activity_start)
if activity_start < 0 or activity_end < 0:
    raise SystemExit("v124 alert activity segment missing")
activity_end += len('\nJAVA\n\n')
a = s[activity_start:activity_end]
a = a.replace(
    '    public static final String EXTRA_NOTIFICATION_ID = "assignment_notification_id";\n    private int notificationId;',
    '''    public static final String EXTRA_NOTIFICATION_ID = "assignment_notification_id";
    public static final String EXTRA_EVENT_TYPE = "assignment_event_type";
    public static final String EXTRA_COURT_NO = "assignment_court_no";
    public static final String EXTRA_TARGET_MEMBER_ID = "assignment_target_member_id";
    public static final String EXTRA_TRACE_ID = "assignment_trace_id";
    private int notificationId;
    private String eventType = "";
    private String courtNo = "";
    private String targetMemberId = "";
    private String traceId = "";''', 1)
a = a.replace('''        String body = getIntent().getStringExtra(EXTRA_BODY);

        LinearLayout panel''', '''        String body = getIntent().getStringExtra(EXTRA_BODY);
        eventType = getIntent().getStringExtra(EXTRA_EVENT_TYPE) == null ? "" : getIntent().getStringExtra(EXTRA_EVENT_TYPE);
        courtNo = getIntent().getStringExtra(EXTRA_COURT_NO) == null ? "" : getIntent().getStringExtra(EXTRA_COURT_NO);
        targetMemberId = getIntent().getStringExtra(EXTRA_TARGET_MEMBER_ID) == null ? "" : getIntent().getStringExtra(EXTRA_TARGET_MEMBER_ID);
        traceId = getIntent().getStringExtra(EXTRA_TRACE_ID) == null ? "" : getIntent().getStringExtra(EXTRA_TRACE_ID);
        NativeDeliveryReporter.reportPath("full_screen_attempted", eventType, courtNo,
                targetMemberId, NativePushRegistrar.currentMemberId(this),
                NativePushRegistrar.isCurrentMember(this, targetMemberId),
                true, true, true, false, false,
                "alert_activity_created", traceId);

        LinearLayout panel''', 1)
a = a.replace('        confirm.setOnClickListener(view -> dismissAlert());',
              '        confirm.setOnClickListener(view -> dismissAlert("center_confirm"));', 1)
a = a.replace('    private void dismissAlert() {\n', '''    private void dismissAlert(String source) {
        String selected = NativePushRegistrar.currentMemberId(this);
        NativeDeliveryReporter.reportPath(
                "center_confirm".equals(source) ? "confirm_action" : "dismiss_action",
                eventType, courtNo, targetMemberId, selected,
                NativePushRegistrar.isCurrentMember(this, targetMemberId),
                true, true, true, true, false, source, traceId);
''', 1)
a = a.replace('''        if (vibrator != null) vibrator.cancel();
        finishAndRemoveTask();''', '''        if (vibrator != null) vibrator.cancel();
        NativeDeliveryReporter.reportPath("vibration_cancelled", eventType, courtNo,
                targetMemberId, selected,
                NativePushRegistrar.isCurrentMember(this, targetMemberId),
                true, true, true, false, true, source, traceId);
        finishAndRemoveTask();''', 1)
a = a.replace('    @Override public void onBackPressed() { dismissAlert(); }',
              '    @Override public void onBackPressed() { dismissAlert("center_back"); }', 1)
for marker in ('EXTRA_EVENT_TYPE', 'alert_activity_created', 'center_confirm'):
    if marker not in a:
        raise SystemExit("v124 activity marker missing: " + marker)
s = s[:activity_start] + a + s[activity_end:]

# Overlay: preserve v1.2.3's CountDownLatch/AtomicBoolean real-add check while
# recording permission, add success/failure and center-confirm execution.
overlay_start = s.find('cat > "$OVERLAY_JAVA" <<\'JAVA\'\n')
overlay_end = s.find('\nJAVA\n\n', overlay_start)
if overlay_start < 0 or overlay_end < 0:
    raise SystemExit("v124 overlay segment missing")
overlay_end += len('\nJAVA\n\n')
o = s[overlay_start:overlay_end]
show_start = o.find('    public static boolean show(Context context, String title, String body, int notificationId) {')
show_end = o.find('    public static void stopEverything(Context context, int notificationId) {', show_start)
if show_start < 0 or show_end < 0:
    raise SystemExit("v124 verified overlay methods missing")
show_method = r'''    public static boolean show(Context context, String title, String body, int notificationId,
                               String eventType, String courtNo, String targetMemberId,
                               String traceId) {
        Context app = context.getApplicationContext();
        String selected = NativePushRegistrar.currentMemberId(app);
        boolean allowed = canShow(app);
        NativeDeliveryReporter.reportPath("full_screen_capability", eventType, courtNo,
                targetMemberId, selected,
                NativePushRegistrar.isCurrentMember(app, targetMemberId),
                false, allowed, false, false, false,
                allowed ? "overlay_permission_allowed" : "overlay_permission_denied", traceId);
        if (!allowed) return false;

        java.util.concurrent.atomic.AtomicBoolean actuallyAdded =
                new java.util.concurrent.atomic.AtomicBoolean(false);
        java.util.concurrent.CountDownLatch finished = new java.util.concurrent.CountDownLatch(1);
        Runnable render = () -> {
            try {
                if (windowManager != null && activeView != null) {
                    try { windowManager.removeView(activeView); } catch (Exception ignored) {}
                    activeView = null;
                }
                windowManager = (WindowManager) app.getSystemService(Context.WINDOW_SERVICE);
                if (windowManager == null) return;

                LinearLayout panel = new LinearLayout(app);
                panel.setOrientation(LinearLayout.VERTICAL);
                panel.setGravity(Gravity.CENTER);
                panel.setPadding(56, 50, 56, 42);
                panel.setBackgroundColor(Color.WHITE);

                TextView heading = new TextView(app);
                heading.setText(title);
                heading.setTextSize(25);
                heading.setTextColor(Color.rgb(12, 49, 126));
                heading.setTypeface(Typeface.DEFAULT, Typeface.BOLD);
                heading.setGravity(Gravity.CENTER);
                panel.addView(heading, new LinearLayout.LayoutParams(-1, -2));

                TextView message = new TextView(app);
                message.setText(body);
                message.setTextSize(21);
                message.setTextColor(Color.BLACK);
                message.setGravity(Gravity.CENTER);
                LinearLayout.LayoutParams messageParams = new LinearLayout.LayoutParams(-1, -2);
                messageParams.setMargins(0, 32, 0, 38);
                panel.addView(message, messageParams);

                Button confirm = new Button(app);
                confirm.setText("확인하고 닫기");
                confirm.setTextSize(19);
                confirm.setOnClickListener(view -> stopEverything(app, notificationId,
                        eventType, courtNo, targetMemberId, traceId));
                panel.addView(confirm, new LinearLayout.LayoutParams(-1, -2));

                int type = Build.VERSION.SDK_INT >= Build.VERSION_CODES.O
                        ? WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY
                        : WindowManager.LayoutParams.TYPE_PHONE;
                WindowManager.LayoutParams params = new WindowManager.LayoutParams(
                        -1, -2, type,
                        WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON |
                                WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN,
                        PixelFormat.TRANSLUCENT);
                params.gravity = Gravity.CENTER;
                windowManager.addView(panel, params);
                activeView = panel;
                actuallyAdded.set(true);
                NativeDeliveryReporter.reportPath("full_screen_attempted", eventType, courtNo,
                        targetMemberId, NativePushRegistrar.currentMemberId(app),
                        NativePushRegistrar.isCurrentMember(app, targetMemberId),
                        false, true, true, false, false, "overlay_added", traceId);
            } catch (Exception ignored) {
                activeView = null;
                actuallyAdded.set(false);
                NativeDeliveryReporter.reportPath("full_screen_attempted", eventType, courtNo,
                        targetMemberId, NativePushRegistrar.currentMemberId(app),
                        NativePushRegistrar.isCurrentMember(app, targetMemberId),
                        false, true, true, false, false, "overlay_add_failed", traceId);
            } finally {
                finished.countDown();
            }
        };

        if (Looper.myLooper() == Looper.getMainLooper()) {
            render.run();
        } else {
            MAIN.post(render);
            try { finished.await(2500, java.util.concurrent.TimeUnit.MILLISECONDS); }
            catch (InterruptedException interrupted) { Thread.currentThread().interrupt(); }
        }
        return actuallyAdded.get();
    }

'''
o = o[:show_start] + show_method + o[show_end:]
o = o.replace('    public static void stopEverything(Context context, int notificationId) {\n', '''    public static void stopEverything(Context context, int notificationId,
                                      String eventType, String courtNo,
                                      String targetMemberId, String traceId) {
        String selected = NativePushRegistrar.currentMemberId(context);
        NativeDeliveryReporter.reportPath("confirm_action", eventType, courtNo,
                targetMemberId, selected,
                NativePushRegistrar.isCurrentMember(context, targetMemberId),
                true, true, true, true, false,
                "overlay_confirm", traceId);
''', 1)
o = o.replace('''        if (vibrator != null) vibrator.cancel();
        NativeDeliveryReporter.report("vibration_cancelled", "", false,
                true, true, true, true);''', '''        if (vibrator != null) vibrator.cancel();
        NativeDeliveryReporter.reportPath("vibration_cancelled", eventType, courtNo,
                targetMemberId, selected,
                NativePushRegistrar.isCurrentMember(context, targetMemberId),
                true, true, true, false, true,
                "overlay_confirm", traceId);''', 1)
for marker in ('AtomicBoolean(false)', 'finished.await(2500', 'overlay_added', 'overlay_add_failed', 'overlay_confirm'):
    if marker not in o:
        raise SystemExit("v124 overlay marker missing: " + marker)
s = s[:overlay_start] + o + s[overlay_end:]

# Notification action and swipe-delete share cancellation semantics but get
# separate PendingIntents so the diagnostic history identifies which path ran.
receiver_start = s.find('cat > "$DISMISS_JAVA" <<\'JAVA\'\n')
receiver_end = s.find('\nJAVA\n\n', receiver_start)
if receiver_start < 0 or receiver_end < 0:
    raise SystemExit("v124 receiver segment missing")
receiver_end += len('\nJAVA\n\n')
r = s[receiver_start:receiver_end]
r = r.replace('    public static final String ACTION_DISMISS = "com.jayuminton.user.DISMISS_ASSIGNMENT_ALERT";', '''    public static final String ACTION_DISMISS = "com.jayuminton.user.DISMISS_ASSIGNMENT_ALERT";
    public static final String EXTRA_SOURCE = "dismiss_source";
    public static final String EXTRA_EVENT_TYPE = "dismiss_event_type";
    public static final String EXTRA_COURT_NO = "dismiss_court_no";
    public static final String EXTRA_TARGET_MEMBER_ID = "dismiss_target_member_id";
    public static final String EXTRA_TRACE_ID = "dismiss_trace_id";''', 1)
r = r.replace('''        NotificationManager notifications =
                (NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);''', '''        String source = intent == null || intent.getStringExtra(EXTRA_SOURCE) == null
                ? "notification_action" : intent.getStringExtra(EXTRA_SOURCE);
        String eventType = intent == null || intent.getStringExtra(EXTRA_EVENT_TYPE) == null
                ? "" : intent.getStringExtra(EXTRA_EVENT_TYPE);
        String courtNo = intent == null || intent.getStringExtra(EXTRA_COURT_NO) == null
                ? "" : intent.getStringExtra(EXTRA_COURT_NO);
        String targetMemberId = intent == null || intent.getStringExtra(EXTRA_TARGET_MEMBER_ID) == null
                ? "" : intent.getStringExtra(EXTRA_TARGET_MEMBER_ID);
        String traceId = intent == null || intent.getStringExtra(EXTRA_TRACE_ID) == null
                ? "" : intent.getStringExtra(EXTRA_TRACE_ID);
        String selected = NativePushRegistrar.currentMemberId(context);
        NativeDeliveryReporter.reportPath(
                "notification_deleted".equals(source) ? "notification_deleted" : "dismiss_action",
                eventType, courtNo, targetMemberId, selected,
                NativePushRegistrar.isCurrentMember(context, targetMemberId),
                true, true, false, true, false, source, traceId);

        NotificationManager notifications =
                (NotificationManager) context.getSystemService(Context.NOTIFICATION_SERVICE);''', 1)
r = r.replace('''        if (vibrator != null) vibrator.cancel();
        AssignmentOverlay.dismissOnly();
        NativeDeliveryReporter.report("vibration_cancelled", "", false,
                true, true, false, true);''', '''        if (vibrator != null) vibrator.cancel();
        AssignmentOverlay.dismissOnly();
        NativeDeliveryReporter.reportPath("vibration_cancelled", eventType, courtNo,
                targetMemberId, selected,
                NativePushRegistrar.isCurrentMember(context, targetMemberId),
                true, true, false, false, true, source, traceId);''', 1)
for marker in ('EXTRA_SOURCE', 'notification_deleted', 'dismiss_action'):
    if marker not in r:
        raise SystemExit("v124 receiver marker missing: " + marker)
s = s[:receiver_start] + r + s[receiver_end:]

# FCM service: context extras, actual NotificationManager success, Android full
# screen capability, verified overlay result and actual vibrator start.
service_start = s.find("cat > \"$SERVICE_JAVA\" <<'JAVA'\n")
service_end = s.find('\nJAVA\n\n', service_start)
if service_start < 0 or service_end < 0:
    raise SystemExit("v124 FCM service segment missing")
service_end += len('\nJAVA\n\n')
f = s[service_start:service_end]

f = f.replace('    private void showNotification(boolean court, String title, String body, String assignmentId) {', '''    private boolean showNotification(boolean court, String title, String body,
                                     String assignmentId, String type, String courtNo,
                                     String targetMemberId) {''', 1)
f = f.replace('        if (manager == null) return;', '        if (manager == null) return false;', 1)
f = f.replace('        alertIntent.putExtra(AssignmentAlertActivity.EXTRA_NOTIFICATION_ID, notificationId);', '''        alertIntent.putExtra(AssignmentAlertActivity.EXTRA_NOTIFICATION_ID, notificationId);
        alertIntent.putExtra(AssignmentAlertActivity.EXTRA_EVENT_TYPE, type);
        alertIntent.putExtra(AssignmentAlertActivity.EXTRA_COURT_NO, courtNo);
        alertIntent.putExtra(AssignmentAlertActivity.EXTRA_TARGET_MEMBER_ID, targetMemberId);
        alertIntent.putExtra(AssignmentAlertActivity.EXTRA_TRACE_ID, assignmentId);''', 1)
f = f.replace('''        dismissIntent.putExtra(AlertDismissReceiver.EXTRA_NOTIFICATION_ID, notificationId);
        PendingIntent dismissPending = PendingIntent.getBroadcast(''', '''        dismissIntent.putExtra(AlertDismissReceiver.EXTRA_NOTIFICATION_ID, notificationId);
        dismissIntent.putExtra(AlertDismissReceiver.EXTRA_SOURCE, "notification_action");
        dismissIntent.putExtra(AlertDismissReceiver.EXTRA_EVENT_TYPE, type);
        dismissIntent.putExtra(AlertDismissReceiver.EXTRA_COURT_NO, courtNo);
        dismissIntent.putExtra(AlertDismissReceiver.EXTRA_TARGET_MEMBER_ID, targetMemberId);
        dismissIntent.putExtra(AlertDismissReceiver.EXTRA_TRACE_ID, assignmentId);
        PendingIntent dismissPending = PendingIntent.getBroadcast(''', 1)

pending_tail = '''                PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE
        );'''
pos = f.find(pending_tail, f.find('PendingIntent dismissPending'))
if pos < 0:
    raise SystemExit("v124 dismiss PendingIntent tail missing")
pos += len(pending_tail)
delete_block = '''
        Intent deleteIntent = new Intent(this, AlertDismissReceiver.class);
        deleteIntent.setAction(AlertDismissReceiver.ACTION_DISMISS + ".delete." + assignmentId);
        deleteIntent.putExtra(AlertDismissReceiver.EXTRA_NOTIFICATION_ID, notificationId);
        deleteIntent.putExtra(AlertDismissReceiver.EXTRA_SOURCE, "notification_deleted");
        deleteIntent.putExtra(AlertDismissReceiver.EXTRA_EVENT_TYPE, type);
        deleteIntent.putExtra(AlertDismissReceiver.EXTRA_COURT_NO, courtNo);
        deleteIntent.putExtra(AlertDismissReceiver.EXTRA_TARGET_MEMBER_ID, targetMemberId);
        deleteIntent.putExtra(AlertDismissReceiver.EXTRA_TRACE_ID, assignmentId);
        PendingIntent deletePending = PendingIntent.getBroadcast(
                this,
                notificationId ^ 0x5A5A,
                deleteIntent,
                PendingIntent.FLAG_UPDATE_CURRENT | PendingIntent.FLAG_IMMUTABLE
        );'''
f = f[:pos] + delete_block + f[pos:]
f = f.replace('.setDeleteIntent(dismissPending)', '.setDeleteIntent(deletePending)', 1)
f = f.replace('        manager.notify(notificationId, builder.build());',
              '        manager.notify(notificationId, builder.build());\n        return true;', 1)

flow_old = '''        configureAlertVolumes();
        int notificationId = assignmentId.hashCode();
        boolean overlayShown = AssignmentOverlay.show(this, title, body, notificationId);
        showNotification(court, title, body, assignmentId);
        boolean fullScreenAllowed = true;
        if (Build.VERSION.SDK_INT >= 34) {
            NotificationManager notificationManager =
                    (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
            fullScreenAllowed = notificationManager != null && notificationManager.canUseFullScreenIntent();
        }
        NativeDeliveryReporter.report("notification_posted", type,
                hasTargetMemberId, true, true, overlayShown, false);
        // Diagnostic build uses a finite waveform so a blocked button can never
        // leave the tester with an unstoppable vibration.
        vibrateStrong(court ? 5 : 3, overlayShown);'''
if f.count(flow_old) != 1:
    raise SystemExit("v124 current v1.2.3 alert-flow anchor missing")
f = f.replace(flow_old, '''        configureAlertVolumes();
        int notificationId = assignmentId.hashCode();
        boolean systemFullScreenAllowed = true;
        if (Build.VERSION.SDK_INT >= 34) {
            NotificationManager notificationManager =
                    (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
            systemFullScreenAllowed = notificationManager != null &&
                    notificationManager.canUseFullScreenIntent();
        }
        NativeDeliveryReporter.reportPath("full_screen_capability", type, courtNo,
                targetMemberId, selectedMemberId, true,
                false, systemFullScreenAllowed, false, false, false,
                "notification_fullscreen", assignmentId);
        boolean overlayShown = AssignmentOverlay.show(this, title, body, notificationId,
                type, courtNo, targetMemberId, assignmentId);
        boolean notificationPosted = showNotification(court, title, body, assignmentId,
                type, courtNo, targetMemberId);
        NativeDeliveryReporter.reportPath("notification_posted", type, courtNo,
                targetMemberId, selectedMemberId, true,
                notificationPosted, systemFullScreenAllowed, false, false, false,
                overlayShown ? "native_notification_overlay_added" : "native_notification_no_overlay",
                assignmentId);
        boolean vibrationActive = vibrateStrong(court ? 5 : 3, overlayShown);
        NativeDeliveryReporter.reportPath("vibration_started", type, courtNo,
                targetMemberId, selectedMemberId, true,
                notificationPosted, systemFullScreenAllowed, false,
                vibrationActive, false, "native_vibrator", assignmentId);''', 1)

f = f.replace('    private void vibrateStrong(int groups, boolean repeatUntilConfirmed) {',
              '    private boolean vibrateStrong(int groups, boolean repeatUntilConfirmed) {', 1)
f = f.replace('        if (vibrator == null || !vibrator.hasVibrator()) return;',
              '        if (vibrator == null || !vibrator.hasVibrator()) return false;', 1)
vibrate_tail = '''        } else {
            vibrator.vibrate(timings, repeatUntilConfirmed ? 0 : -1);
        }
    }
}'''
if f.count(vibrate_tail) != 1:
    raise SystemExit("v124 vibrator return anchor missing")
f = f.replace(vibrate_tail, '''        } else {
            vibrator.vibrate(timings, repeatUntilConfirmed ? 0 : -1);
        }
        return true;
    }
}''', 1)

for marker in (
    'boolean notificationPosted = showNotification',
    'notification_fullscreen',
    'vibration_started',
    'deletePending',
    'AssignmentOverlay.show(this, title, body, notificationId,',
):
    if marker not in f:
        raise SystemExit("v124 FCM marker missing: " + marker)
s = s[:service_start] + f + s[service_end:]

for marker in (
    'VERSION="1.2.4"',
    'VERSION_CODE="124"',
    'class NativeDeliveryReporter',
    'reportPath("fcm_received"',
    'reportPath("member_rejected"',
    'reportPath("member_accepted"',
    'reportPath("notification_posted"',
    'reportPath("full_screen_capability"',
    'reportPath("full_screen_attempted"',
    'reportPath("confirm_action"',
    'reportPath("vibration_cancelled"',
    '"token_register_requested"',
    '"token_register_http_ok"',
    '"token_register_http_failed"',
    '"notification_deleted"',
    '"확인 · 진동 끄기"',
    'confirm.setText("확인하고 닫기")',
    '"대기 1순위입니다. 라켓 들고 준비하세요."',
    'courtNo + "번 코트로 들어가세요."',
    '.setDeleteIntent(deletePending)',
    'android.permission.SYSTEM_ALERT_WINDOW',
    'AtomicBoolean(false)',
    'finished.await(2500',
    'NativePushRegistrar.currentMemberId',
):
    if marker not in s:
        raise SystemExit("missing native v1.2.4 diagnostic marker: " + marker)

path.write_text(s, encoding="utf-8")
print("Prepared v1.2.4 receive-path diagnostic on the verified v1.2.3 overlay base; live routing untouched.")
